### ISSUE TITLE
consider publishing to npm

### ISSUE THREAD

**Issue by omarkhatibco** [davidcetinkaya/embla-carousel#1]
Hi @davidcetinkaya 

I tried to test the slider but seems you did not published it to npm.

**Comment by davidcetinkaya** [comment]
@omarkhatibco, Wow! You're fast =). I will publish it as soon as possible. Just need to add some examples and adjust some stuff first.

**Comment by davidcetinkaya** [comment]
Package is now published on **NPM**, here's a [link](https://www.npmjs.com/package/embla-carousel). I'm closing this issue.
