### ISSUE TITLE
 The slides are not showing at the end of the carousel with a large number of slides.

### ISSUE THREAD

**Issue by duza** [davidcetinkaya/embla-carousel#100]
I used your example with `Variable Widths` and changed the number of slides https://codesandbox.io/s/embla-carousel-variablewidths-react-forked-4nshv You can see that 11 last slides are not showing. Also, I output scroll positions and got
```
console.log(embla.scrollSnapList());
[0, 0.07338388461443308, 0.20792409885950375, 0.3302336656688356, 0.47700452734964505, 0.6176616115385568, 0.7093961059845131, 0.8684007075530048, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```
The snap point positions for last 12 slides equals to 1. Is it normal?

**Comment by davidcetinkaya** [comment]
Hello @duza,
I can only see 9 slides in your forked sandbox?

![CE7C1E1A-9A52-4E59-98C8-41F383F32992](https://user-images.githubusercontent.com/11529148/92566518-a1a47e80-f27c-11ea-99cd-2d8c170f4354.jpeg)

Did you forget to update it?

**Comment by duza** [comment]
Hi @davidcetinkaya, sorry I forgot to save it :(  I saved changes now for forked version. Make sure that the problem exists.

**Comment by davidcetinkaya** [comment]
Thanks @duza, I will take a look at it as soon as possible and let you know when I have something.

**Comment by davidcetinkaya** [comment]
@duza you haven’t specified any base width for the slides? As you can see in the CSS slide 1 to 9 all have widths specified.

![06E7B989-7910-4D1C-B2F1-67CCEFED4BE6](https://user-images.githubusercontent.com/11529148/92567417-f5fc2e00-f27d-11ea-9ba1-fd49a173a59a.jpeg)

Let me know if it works.

Best
David

**Comment by duza** [comment]
@davidcetinkaya Yeap, you are right. Thank you very much

**Comment by davidcetinkaya** [comment]
@duza no worries. Congratulations, you opened issue number #100 😃. Enjoy!

Kindly 
David

**Comment by duza** [comment]
@davidcetinkaya But you know, when I fixed width in css the last slide didn't show at all.

**Comment by davidcetinkaya** [comment]
Have you updated the CodeSandbox so I can take a look?

**Comment by duza** [comment]
Sorry, It's my fault again, I didn't set the width for the last one, 20th. You can close this issue. Thank you.
