### ISSUE TITLE
Does it possible add slides dynamically?

### ISSUE THREAD

**Issue by etozhkirill** [davidcetinkaya/embla-carousel#103]
I have some items in carousel and I want to load another part of items on last swipe and after this I want to continue swiping from last snap point. How can I detect last swipe and add new slides dynamically?

**Comment by khannea** [comment]
My life would also be brighter if I could add/remove slides.
This carousel is super great, but without adding slides, I can't use it... 

If I add slides, I can see them after but the caroussel constraints prevent me from putting them in view. 
If I ReInit() the caroussel after slides added, the prevent click if isMove is no more working.

**Comment by davidcetinkaya** [comment]
Hello @etozhkirill and @khannea,

Thank you for this feature request. This is more or less the same request as issue #89 so I'm going to close this. Let's continue the discussion there.

Kindly,
David
