### ISSUE TITLE
IOS Picker Loop doesn't render correctly in IE11

### ISSUE THREAD

**Issue by Sinmok** [davidcetinkaya/embla-carousel#104]
On the examples page, there's an "IOS Picker" picker example at the bottom of the page. These pickers do not render correctly in IE11.

Just flagging as the docs mention support for IE11!

See screenshot
![image](https://user-images.githubusercontent.com/4395573/93338545-5e20b600-f822-11ea-8afb-a489b7f6ed7f.png)

**Comment by davidcetinkaya** [comment]
Hello @Sinmok,

Thank you for sharing this and the helpful screenshot demonstrating the issue. All other examples seem to work in IE11 so I’m guessing this could be related to the 3D transforms. Maybe it’s as simple as adding prefixes, maybe it’s more complicated.

I have a lot to do right now, like updating the documentation, adding new features, resolving bugs, improving the core, reducing the bundle size and you name it...

So feel free to help out if you don’t mind investigating this a bit. 

Best
David

**Comment by davidcetinkaya** [comment]
This is probably related to the missing support for `transform-style: preserve-3d` in IE11 ([StackOverflow post](https://stackoverflow.com/questions/22848328/css3-3d-transform-doesnt-work-on-ie11)).

**Comment by davidcetinkaya** [comment]
Note to self: Only `perspective-origin` fix for IE11 left to do.

**Comment by davidcetinkaya** [comment]
Hello again @Sinmok,

I've shipped a fix for the IOS pickers. Would you mind testing them in IE11 again? Please let me know if you're intending to do so.

Thanks in advance,
David

**Comment by davidcetinkaya** [comment]
Hello again @Sinmok.

You didn't reply to my first message so I'm going to assume that you won't do it now either. I've tested my fix in IE11 a lot and it should work as expected now. Feel free to re-open this issue if you're still experiencing issues in IE11 though.

**Comment by Sinmok** [comment]
@davidcetinkaya Sorry for the delay. I've retested and I can confirm this is fixed.

**Comment by davidcetinkaya** [comment]
@Sinmok thanks a lot for taking time to test it. I’m glad it works as expected now.

Kindly,
David
