### ISSUE TITLE
Forward embla up in the hierarchy using React

### ISSUE THREAD

**Issue by ianmethyst** [davidcetinkaya/embla-carousel#111]
First of all, congratulations on developing Embla, It's a great library!

I'm trying to interact programmatically with Embla from a component that it's higher in a React component hierarchy, but I cannot figure how to do it. I have a `<Container>` component that renders another component with the carousel (`<EmblaCarousel>`), but I want to use a hook in `<Container>` (potentially `useEffect`), that access the carousel and calls its `scrollTo()`. I cannot nest the `<Container>` in `EmblaCarousel>`. Is there a way to do this? I tried using `React.forwardRef` in `<EmblaCarousel>`, but I couldn't figure how to use it to achieve what I have in mind.

Thanks in advance!

**Comment by davidcetinkaya** [comment]
Hello Ian (@ianmethyst)! Thanks a lot. That's encouraging to hear.

Which version of Embla Carousel are you using? Are you using version 4 or later where Embla is initialized with a ref, like [described in the documentation](https://davidcetinkaya.github.io/embla-carousel/#react-usage)?

Kindly,
David

**Comment by ianmethyst** [comment]
I'm using v4+ as shown in the documentation. I want to know if `emblaApi`, the second element returned by `useEmblaCarousel()` can be accessed from outside that component somehow.

As an off-topic, is there a way to disable dragging and re enable it without recreating the carousel? (if it is not possible, I can open another issue as a feature request)

**Comment by davidcetinkaya** [comment]
Hello again Ian (@ianmethyst),

Thank you for the additional details. I've setup a [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-111-i3xuf) that demonstrates how to forward the `ref`, in order to access the `emblaApi` higher up in the hierarchy.

Let me know if it helps and if this is what you had in mind.

Best,
David

**Comment by davidcetinkaya** [comment]
Hello Ian (@ianmethyst),

Have you had the change to try the [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-111-i3xuf) I created and mentioned [here](https://github.com/davidcetinkaya/embla-carousel/issues/111#issuecomment-712758200) yet?

Kindly,
David

**Comment by ianmethyst** [comment]
Thank you for your time, and sorry for the late response! Yes, this solved my problem, I didn't realize I could just move the hook up and use React.forwardRef this way 

The use case for the off topic question is that I have a carousel that have some items that are zoomable and draggable, and I'd like to disable the drag event in the carousel when an image is zoomed and enable it again when the zoom is reset. I thought I could use reinit, but I was wondering if this would have some kind of performance impact. Sorry if this is a silly question and using reInit is the way to go, I didn't have the time to test it out

**Comment by davidcetinkaya** [comment]
No worries Ian (@ianmethyst),

Thanks for the response. I wast just curious if it helped. And I'm glad to hear that it helped, so I'm closing this issue as **resolved** 👍. I pretty much followed the example in the official [documentation page](https://reactjs.org/docs/forwarding-refs.html) for `React.forwardRef`.

About the off-topic request. I don't think your app will suffer a performance hit unless you're calling `embla.reInit()` repeatedly, like 100 times a second or similar. You're welcome to create a feature request for this, although I can't promise that I will choose to add it to the Embla Carousel core.

Kindly,
David
