### ISSUE TITLE
Custom hook to rebuild Embla in React?

### ISSUE THREAD

**Issue by phyominh** [davidcetinkaya/embla-carousel#116]
Hi,
I was following [the code sandbox](https://codesandbox.io/s/embla-carousel-ios-picker-default-react-fotej?file=/src/js/EmblaWheel.js) for iOS style picker.
For my use case I have to update the carousel items when props change. And when items are updated the styling got messed up and items will no longer snap in the selection box. So I think the only solution is to rebuild embla instance. Is there a custom hook for rebuilding it? If there is none can you give some advice on how to customize it?

**Comment by davidcetinkaya** [comment]
Hello @phyominh,

Thank you for your question. Try something along these lines:

```ts
const reloadPicker = useCallback(() => {
  if (!embla) return
  setWheelReady(false)
  setWheelReady(() => {
    embla.reInit()
    embla.dangerouslyGetEngine().translate.toggleActive(false)
    setRotation()
    return true
  })
}, [embla, setWheelReady, setRotation])

useEffect(() => {
  reloadPicker()
}, [reloadPicker, /* add your props here as dependency */])
```

Let me know if it helps!

Best,
David

**Comment by davidcetinkaya** [comment]
@phyominh, did you see my response?

**Comment by phyominh** [comment]
@davidcetinkaya Oh, sorry for the late response. I didn't get the notification for the first reply.
Yes, this solves the styling problem. Thank you very much for your answer and thanks for this library. You can close the issue now.

**Comment by davidcetinkaya** [comment]
@phyominh no worries, thanks for getting back to me. I'm glad it worked!

I just want to mention that the iOS style pickers **didn't render correctly in IE11** (issue #104). When I first created the pickers, I didn't know that IE11 didn't support the following CSS: `transform-style: preserve-3d;`.

But I've fixed this issue and updated the CodeSandboxes. So in case you need to **support IE11**, please update your code to match the following sandbox:

- [iOS Picker (IE11 support)](https://codesandbox.io/s/embla-carousel-ios-picker-default-react-fotej)

Kindly,
David
