### ISSUE TITLE
Question. How to temporary disable slide switching?

### ISSUE THREAD

**Issue by max-mykhailenko** [davidcetinkaya/embla-carousel#117]
I have zoom module inside the embla and I want to disable ability to switch slide when user zoom in. Is it possible?

**Comment by davidcetinkaya** [comment]
Hello Max (@max-mykhailenko),

Thank you for your question. I'm missing some important details in order for me to help you out:

- What action triggers the zoom mode? A click? Pinch move?
- Are you using the VanillaJS or ReactJS version of Embla Carousel?

Kindly,
David

**Comment by davidcetinkaya** [comment]
@max-mykhailenko, did you see my response?

**Comment by max-mykhailenko** [comment]
> * What action triggers the zoom mode? A click? Pinch move?
On desktop it's click and drag after click. I have in place image zoom.
On mobile — pinch gesture.

> * Are you using the VanillaJS or ReactJS version of Embla Carousel?
I use react version of embla carousel and I can run some Embla methods when user starts to pinch or click on the image.

Thank you, for your fast reaction

**Comment by davidcetinkaya** [comment]
Hello again Max (@max-mykhailenko),

Thanks for getting back to me. You didn't provide a **CodeSandbox** so I don't know any details about your setup. But I'm going to try to help you out anyway 🙂.

Assuming that you can make the zoom trigger more consistent on desktop and mobile, by triggering it on a click event, you can do something along these lines:

```ts
const onSlideClick = useCallback((clickedSlideIndex) => {
  if (embla && embla.clickAllowed()) {

    // Re-initalize Embla without pointer interactions
    embla.reInit({ draggable: false }); 

    // Activate zoom here because Embla says the pointer interaction was a click and NOT a drag move
  }
}, [embla]);
```

...and attach the click handler to your slides in your render method:
```jsx
<div className="embla__container">
  {slides.map((slide, slideIndex) => {
    return (
      <div className="embla__slide" onClick={() => onSlideClick(slideIndex)}>
        ...
      </div>
    )}
  )}
</div>
```
...and don't forget to make Embla draggable again when the user closes the zoom, like so:

```ts
embla.reInit({ draggable: true }); 
```
Let me know if this helps.

Best,
David

**Comment by max-mykhailenko** [comment]
> embla.reInit({ draggable: true }); 

Will reinit provoke active slide changes or I'll active slide will be the same?

**Comment by davidcetinkaya** [comment]
@max-mykhailenko,  the active slide will be the same. If `embla.reInit()` is triggered when the active slide is 3, it will re-initialize with slide 3 being active.

Let me know how it goes!

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hello @max-mykhailenko,

How did it go? Have you had any luck with my suggestions?

Best,
David

**Comment by max-mykhailenko** [comment]
> Hello @max-mykhailenko,
> 
> How did it go? Have you had any luck with my suggestions?
> 
> Best,
> David

will check today

**Comment by max-mykhailenko** [comment]
It works fine, thank you

**Comment by davidcetinkaya** [comment]
I'm happy to hear that @max-mykhailenko. Enjoy!

**Comment by ineshbose** [comment]
I'm trying to achieve this, I don't believe there's a `draggable` option in the latest version, so rather switching `active: false`, but the active slide jumps to the first. 🤔

**Comment by davidjerleke** [comment]
Hey @ineshbose,
You can pass a callback to `watchDrag` like this:

```tsx
const isDraggable = useRef(true);

const [emblaRef, emblaApi] = useEmblaCarousel({
  watchDrag: () => isDraggable.current,
});
```

Then, just update the `isDraggable` **ref** to `true` or `false` depending on whether you want to enable or disable drag behavior.
