### ISSUE TITLE
Deprecation warning message for embla-carousel-react users

### ISSUE THREAD

**Issue by davidspiess** [davidcetinkaya/embla-carousel#119]
I had absolutely no idea **embla-carousel-react** was moved into the **embla-carousel** package. NPM always told me i had the newest version, so i missed two major version updates. 
Can you release a new minor **embla-carousel-react** version, which informs the users that the package is abandoned? (https://github.com/dylang/shortid package did this recently too). There are still more than 2000 downloads each week for the old package, so maybe there are some other people out there not knowing about this.

**Comment by davidcetinkaya** [comment]
Hello David (@davidspiess),

Thank you sharing this. Your suggestion makes a lot of sense! I've officially deprecated the package by following the guidelines in the [NPM docs](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-an-entire-package).

Would you mind verifying that you get the deprecation notice with the following message (in red) when you try to install the [embla-carousel-react](https://github.com/davidcetinkaya/embla-carousel-react) package?

<img width="1287" alt="deprecation-notice" src="https://user-images.githubusercontent.com/11529148/99577943-5c1ed300-29dc-11eb-9796-5445bb5dd174.png">

By the way, how did you notice that it was deprecated? Just curious how it came to your knowledge.

Thanks in advance,
David

**Comment by davidspiess** [comment]
Hi David!
Awesome! Now i get a warning in NPM!
![image](https://user-images.githubusercontent.com/992674/99583199-6db7a900-29e3-11eb-9aa5-9a62edf3b700.png)

> By the way, how did you notice that it was deprecated?

It was a coincidence. I updated to React 17 and got a warning that **emba-carousel-react** requires a peer dependency of React 16. So i went to the repo to report that. 😋

**Comment by davidcetinkaya** [comment]
Thanks for confirming David (@davidspiess). Ah I see. In that case, you have catching up to do 😅. Read more here:

- [Major version 3 release](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.0)
-[Major version 4 release](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.0)

Thank you for creating this issue.
Enjoy!

**Comment by davidspiess** [comment]
Already upgraded, it was painless, thanks!
