### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by henrijs** [davidcetinkaya/embla-carousel#126]
For carousels with various height slides, and option to recalculate/change height of view-port would be beneficial. Often images comes with captions of various heights, for example.

**Comment by davidcetinkaya** [comment]
Hello @henrijs,

Than you for your feature request. This is a duplicate of issue #57 

- If you're interested in my reasoning about this feature request, read the whole [issue here](https://github.com/davidcetinkaya/embla-carousel/issues/113).
- If not, jump directly to the [solution](https://github.com/davidcetinkaya/embla-carousel/issues/113#issuecomment-718972448).

Kindly,
David

**Comment by davidcetinkaya** [comment]
Duplicate of #113.
