### ISSUE TITLE
Full screen events

### ISSUE THREAD

**Issue by henrijs** [davidcetinkaya/embla-carousel#127]
How about some additional events on carousel? For example `enter-fullscreen` and `exit-fullscreen`? There is no need for any code, that can be added by implementer, but these events could give a place to

- re-calculate few things,
- add classes to part of carousel I want to be shown larger,
- manipulate sizes attribute on image,
- bind `esc` key to close button,
- enable and disable focus trap and scrolling behind full screen.

Or maybe this is already possible in some graceful manner? I could work with `resize`.

P.S. Like your code.

**Comment by davidcetinkaya** [comment]
Hello @henrijs,
Thank you for your feature request.

I'm thinking that if a user implements full screen events for the carousel, the user has to add [full screen listeners](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event#Examples) to the document anyway. Maybe adding these events to Embla Carousel will create an unnecessary layer of logic? Embla calls its `embla.reInit()` method on the window resize event and does all the necessary calculations automatically.

Extending the [example code from the MDN site](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event#Examples) for fullscreen events, something along these lines should work:

```ts
function onEmblaEntersFullScreen(fullscreenElement) {
  // Determine if fullscreenElement is the embla wrapper.
  // Do your magic like binding the ESC key and so on...
}

document.addEventListener('fullscreenchange', (event) => {
  // document.fullscreenElement will point to the element that
  // is in fullscreen mode if there is one. If there isn't one,
  // the value of the property is null.
  if (document.fullscreenElement) {
    onEmblaEntersFullScreen(document.fullscreenElement)
    console.log(`Element: ${document.fullscreenElement.id} entered full-screen mode.`);
  } else {
    console.log('Leaving full-screen mode.');
  }
});
```

With that said. Do you want me to create a CodeSandbox demonstrating this?

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hi again @henrijs,

Have you had the chance to read my [response](https://github.com/davidcetinkaya/embla-carousel/issues/127#issuecomment-739909361) yet?

Best,
David

**Comment by davidcetinkaya** [comment]
Closing this due to lack of response.

**Comment by DennisKraaijeveld** [comment]
I would be interested in an example. Fullscreen mode would be awesome. Do you mind looking into it again?

**Comment by davidcetinkaya** [comment]
Hi @DennisKraaijeveld,

A lot has happened since this issue was created. As of v6 Embla accepts plugins so I think a full screen plugin should be created. I’ve added this to the plugin list for possible future plugins:

- #237

Best,
David

**Comment by romatou** [comment]
@davidjerleke, any updates on fullscreen plugins or examples?
