### ISSUE TITLE
How could I add a button with scrollNext on each slide as in the image?

### ISSUE THREAD

**Issue by lorenzecode** [davidcetinkaya/embla-carousel#133]
Hi,
How could I add a button with scrollNext on each slide as in the image?

I'm still new to javascript
I'm sorry for the english from google translator

![carousel](https://user-images.githubusercontent.com/61021547/103307719-8908d180-49ef-11eb-86c8-079291bcd2ce.jpg)

**Comment by davidcetinkaya** [comment]
Hi @lorenzecode,

Thank you for your question. Are you using Embla with Vanilla JavaScript or React?

Best,
David

**Comment by lorenzecode** [comment]
Thanks for answering

Currently in Vanilla JS

**Comment by davidcetinkaya** [comment]
Thank you for the details @lorenzecode.

For example, if your buttons have the **classname** `.scroll-next-button`, you could do something along these lines:

```ts
const scrollNextOnSlideButtonClick = () => {
  // embla.clickAllowed() only returns true if the pointer interaction is a click, not if it is a drag move.
  if (embla.clickAllowed()) {
    embla.scrollNext();
  }
}

embla.slideNodes().forEach((slideNode) => {
  const scrollNextButton = slideNode.querySelector('.scroll-next-button');
  scrollNextButton.addEventListener('click', scrollNextOnSlideButtonClick, false);
});
```

Let me know if it helps.

Best,
David

**Comment by lorenzecode** [comment]
Hi, @davidcetinkaya 

Would it be too much to ask for an example with the images of the cats?

I tried your solution here but I must be doing something wrong

Thanks again and sorry for the inconvenience

**Comment by davidcetinkaya** [comment]
Hello @lorenzecode,

Would you mind creating a CodeSandbox with your setup and share the link here? I can modify your sandbox and show you how to achieve what you want.

Kindly,
David

**Comment by davidcetinkaya** [comment]
@lorenzecode, here's a [CodeSandbox](https://codesandbox.io/s/embla-carousel-vanilla-github-issue-133-q1mty) demonstrating what you want to achieve.

Let me know if it helps.

Best,
David

**Comment by lorenzecode** [comment]
Wow @davidcetinkaya is exactly that

Thank you very much

**Comment by davidcetinkaya** [comment]
You're welcome @lorenzecode. I'm closing this issue as resolved then. Enjoy!
