### ISSUE TITLE
 seems carousel is broken

### ISSUE THREAD

**Issue by JeffreyOdogba** [davidcetinkaya/embla-carousel#137]
I appreciate everyone who participated in the embla-carousel.

After my implementation, It worked at first or when I make a change on the code initially but when I refresh the page it breaks i.e carousel doesn't move, carousel doesn't respond to the next button.  I believe I did the implementation right, I can't figure out where this issue is coming from.

If any hint please let me know, I really enjoy embla-carousel.

Don't work
![1](https://user-images.githubusercontent.com/15901735/105285691-e7564980-5b82-11eb-8268-d6c21b032096.PNG)

Works after some initial change or break and hot reload
![2](https://user-images.githubusercontent.com/15901735/105285692-e7564980-5b82-11eb-8e08-627d046e4e94.PNG)

 
Core Code 

 const [viewportRef, embla] = useEmblaCarousel({ align: "center", loop: true });
  
  const [nextBtnEnabled, setNextBtnEnabled] = useState(false);
  const scrollNext = useCallback(() => embla && embla.scrollNext(), [embla]);
  const onSelect = useCallback(() => {
    if (!embla) return; 
    setNextBtnEnabled(embla.canScrollNext());
  }, [embla]);

  useEffect(() => {
    if (!embla) return;
    embla.on("scroll", onSelect);
    onSelect();
  }, [embla, onSelect]);

**Comment by davidcetinkaya** [comment]
Hi Jeffrey (@JeffreyOdogba),

Thank you for your question. Please provide a CodeSandbox with your setup that demonstrates the issue. I need that in order to debug properly and see why this is happening.

You may create your own CodeSandbox or fork [this CodeSandbox](https://codesandbox.io/embed/embla-carousel-loop-react-brro5?codemirror=1). Please make sure to use the same Embla Carousel package version that you’re using now.

Thanks in advance.

Kindly,
David

**Comment by JeffreyOdogba** [comment]
I did some debugging myself and I got to notice the issue seems to occur when I add a custom styling to take that form of the {WORK} screen shoot in my project. It could be I am not styling it right. 

 
[https://codesandbox.io/s/embla-carousel-loop-react-forked-wxkwx?fontsize=14&hidenavigation=1&theme=dark](I did a test CodeSandbox) no bug or breaks. will still keep debugging. 

If you can replicate my styling and run into the same issue that will be somewhat cool. Thanks again.

**Comment by davidcetinkaya** [comment]
Hello again Jeffrey (@JeffreyOdogba),

Sorry, I'm not following. At this point, I don't have a clear picture of the issue you're experiencing. Were you able to reproduce it in the CodeSandbox you shared in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/137#issuecomment-764725403)?

Kindly,
David

**Comment by davidcetinkaya** [comment]
@JeffreyOdogba I’m closing this for now. Feel free to re-open this issue if you’re able to reproduce it.

Best,
David
