### ISSUE TITLE
Multiple slides selected in iOS Picker example

### ISSUE THREAD

**Issue by x4th** [davidcetinkaya/embla-carousel#138]
I'm not sure if this is a global bug or just something pertaining to the setup for this example.

Here's a minimal reproducible example on [CodeSandbox](https://codesandbox.io/s/embla-carousel-ios-picker-loop-react-multiple-select-bug-leqgb?file=/src/js/EmblaWheel.js).

After some number of swipes more than one number turns red.

**Comment by davidcetinkaya** [comment]
Hi @x4th,

Thank you for your question. Try adding this line to your options: 

```ts
const [viewportRef, embla] = useEmblaCarousel({
  loop,
  inViewThreshold: 0.5, // Add this line
  axis: "y",
  dragFree: true,
  draggableClass: "",
  draggingClass: "",
  selectedClass: "embla__wheel__slide--selected"
});
```

Does that solve the issue?

Best,
David

**Comment by x4th** [comment]
That does solve the issue, thanks for the quick reply!

I looked at this option [in the docs](https://davidcetinkaya.github.io/embla-carousel/api) now and there it says that the default is 0.5, is that a mistake? [In the code it seems to be set to 0](https://github.com/davidcetinkaya/embla-carousel/blob/f096d82f9a203551f1ed0f2feb2fc5c98241d098/src/vanilla/components/options.ts#L34) and then later on the value of [0.01 seems to be used if it's not set](https://github.com/davidcetinkaya/embla-carousel/blob/9b8d391cae304640f3f747b1cfbe70f45c325cd1/src/vanilla/components/slidesInView.ts#L25)? So I suppose in the iOS picker another slide would be considered in view, given that it was so sensitive?

Thanks for making this library.

**Comment by davidcetinkaya** [comment]
Nice catch. Thanks for pointing that out! Default for that option is as you say 0 (which is internally altered to 0.01 to cover rounding issues).
I’m re-building the documentation page with Gatsby so I’ll make sure to change that. 

At the time of writing, I’m not sure why this is happening, but I’m guessing that it’s related to the **in view** logic somehow. I’ll have to dig deeper when I have time to do so.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hello @x4th,

I've looked into this now. Long story short, extending the carousel with 3D transforms, which is the case for the iOS Pickers, disrupts the internal `slidesInView` logic. Instead of using the built-in logic, you can easily track the current slide index manually by using `embla.selectedScrollSnap()`.

Something along these lines should work:

```jsx
 const [selectedIndex, setSelectedIndex] = useState(0);

...

  useEffect(() => {
    if (!embla) return;

    embla.on("select", () => setSelectedIndex(embla.selectedScrollSnap()));
  }, [embla, setSelectedIndex]);

...

{slideStyles.map((slideStyle, index) => (
  <div
    key={index}
    className={`embla__wheel__slide ${index === selectedIndex ? "embla__wheel__slide--selected" : ""}`}
    style={wheelReady ? slideStyle : { transform: "none" }}
  >
    {index}
  </div>
))}

...
```

And don't forget to opt-out from the classname toggling like so:

```js
  const [viewportRef, embla] = useEmblaCarousel({
    loop,
    axis: "y",
    dragFree: true,
    draggableClass: "",
    draggingClass: "",
    selectedClass: "" // Pass an empty string here
  });
```

Let me know if it helps.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi again @x4t,

I’m closing this issue as resolved. Feel free to try out the [suggested approach](https://github.com/davidcetinkaya/embla-carousel/issues/138#issuecomment-784193078) if you want.

If you don’t think that this issue is resolved, you may open it again.

Best
David
