### ISSUE TITLE
Nested embla carousel - child carousel is causing parent carousel to scroll on drag

### ISSUE THREAD

**Issue by lmcq** [davidcetinkaya/embla-carousel#141]
Hi,

This is a bit of a unique use case, but we need to nest a carousel within a carousel slide (we've essentially got a carousel of cards, and within each card is a carousel of images).

When we drag the slides for the inner carousel, then we don't want the event to bubble up to the parent carousel and therefore cause that to scroll too. However, it seems that attempting to drag the inner carousel also causes the parent to scroll.

I've created a minimal repro here: [https://codesandbox.io/s/nested-embla-bvo96](https://codesandbox.io/s/nested-embla-bvo96)

Interestingly, it seems that events are successfully being prevented from propagation (clicking outside the inner carousel logs out "mouse down", but inside of it does), but the parent carousel still scrolls.

This could just be an implementation error on our side.

Great library, thanks!

**Comment by davidcetinkaya** [comment]
Hi Lewis (@lmcq),

Thank you for your question. Embla Carousel has no official support for nesting carousels, but I’ll try an unofficial way to achieve what you want.

I’ll let you know when I’ve done so.

Kindly,
David

**Comment by lmcq** [comment]
Great, thank you @davidcetinkaya!

**Comment by davidcetinkaya** [comment]
Hello Lewis (@lmcq),

Just wanted to mention that the pressure on this lib is high right now (I'm the sole maintainer of this project), so I don't know when I will have the time to look into this. I thought it would be good to mention that so you can look for alternatives if you need this feature soon.

I hope you understand.

**Comment by lmcq** [comment]
Ok, no problem - thanks for your response!

**Comment by davidcetinkaya** [comment]
Hello Lewis (@lmcq),

I started looking into this yesterday and came to the conclusion that I don't have a clear picture of how this should work. For example, what should happen in this case:

- If I drag the parent carousel and it's halfway to the next slide, transitioning
- And I start dragging the nested carousel inside it

How should the parent carousel respond to this?

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hi Lewis (@lmcq),

So I finally got half an hour to create an example for you. Here's the [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-141-eg8b1) with nested Embla Carousels.

Please let me know if you're intending to check this out or not.

Best,
David

**Comment by lmcq** [comment]
Hi David,

That works great! We'll definitely be looking at using this. Thanks for taking the time to creating this 

Apologies for not getting back to you earlier

Thanks,
Lewis

**Comment by davidcetinkaya** [comment]
Thank you for your response and supporting this project Lewis (@lmcq) 👍🏻. I’m closing this issue as resolved then. Let me know if you run into any issues with the implementation.

Enjoy,
David

**Comment by davidjerleke** [comment]
See [this gist](https://github.com/davidjerleke/embla-carousel/issues/468#issuecomment-1568046576) for nested carousel using v8.
