### ISSUE TITLE
Are .scrollProgress and .selectedScrollSnap unavailable, if loop: true?

### ISSUE THREAD

**Issue by Hahlh** [davidcetinkaya/embla-carousel#143]
Good day, David & Friends!

First of all, thank you very much for creating this and maintaining it in such an incredible manner. 
I just fought my way through 3 other repos and ended up here after a lot of frustration.

I would like to create an infinite loop, while showing the current slide as a fraction:
![image](https://user-images.githubusercontent.com/45669613/108802355-61218e80-7598-11eb-84f3-afada87e5134.png)

If I understand right, .scrollProgress and .selectedScrollSnap become unavailable, if loop is set to true?

I suppose this is by design, but if not, please tell me and I will create a codesandbox demo.

All the best,

Leo

**Comment by davidcetinkaya** [comment]
Hi @Hahlh,

Thank you. They’re both available when `loop: true`. What do you want to achieve?

Kindly
David

**Comment by Hahlh** [comment]
Hey David!

Thank you for the fast answer. 
I thought that I had it reproduced with one of the example codeboxes earlier. Now I tried to build an example for you again and can't. I must have called selectedScrollSnap at some wrong place so that the rerendering or something similar screwed up the count. 
Now calling the mehtod using the callbacks for prev and next works like a charm. 

I will close this and reopen, if really necessary.

Thanks again!

**Comment by davidcetinkaya** [comment]
Hi again @Hahlh,

I’m glad you got it sorted! Thanks for getting back to me and enjoy.
