### ISSUE TITLE
Gatsby - On route change embla looses slides

### ISSUE THREAD

**Issue by Hahlh** [davidcetinkaya/embla-carousel#144]
Hey David!

Hope you are doing great.

Using Gatsby the slide I built works fine until I change to another page that uses the slider as well:

https://user-images.githubusercontent.com/45669613/109027254-e30cd700-76c0-11eb-92e3-7bdb10cbb5ea.mp4

It seems, that although next etc still triggers, the slider looses the node list / slides.
I tried to force reinit with useEffect, but to no avail. 

Interestingly the sliders starts to work again, when I change options, like for example draggable, but that could be of course because of the development hot reload.

Are you familiar with this issue?
What procedure would you suggest for this case for debugging?

Thank you and all the best!

**Comment by davidcetinkaya** [comment]
Hi @Hahlh,

Thank you for your question. My initial hunch is that this isn’t an issue with Embla, because I’ve used Embla with Gatsby before without any issues. But I think I need to see some code to try to understand why this is happening.

Best,
David

**Comment by vladtabachuk** [comment]
what about refreshing embla script each time when route changes? for example remove sctipt tag and add it dynamicly?

**Comment by Hahlh** [comment]
Hey @vladtabachuk ! 

Thank you for jumping in as well.
I didn't answer so far, because I tried to further boil it down to some possibilities. 

Interestingly reInit on each next or prev call solves it, but causes a ton of unnecessary rerenders and causes the image to be refetched every time, if I am not mistaken. At the same time reInit in the useEffect hooks doesn't show any effects, which already hints at the source of the problem, I believe.
 
I have a deadline coming up the 3rd and will have to focus on other things until then, but as soon as that deadline passes, I will be able to properly debug again and hopefully also close this with a solution that will help others stumbling over the same issues.

@davidcetinkaya I hope it is okay for you to keep this open until then. If not, we can close it and I will comment and explain, when I have found a solution. 

Thank you to you of course as well! Your answer times and dedication are impressive and I am glad, that I have found this repo!

**Comment by vladtabachuk** [comment]
Thank you for the kind words, i realy like this embla plugin, and currently using it on my website, what about to link `embla.css` inside header of page, if it doesnt change dynamicly, if your app is SPA, maybe `<link rel="stylesheet" href="/static/js/libs/embla/embla.css">` will be better than `import "./styles.css";` inside js that loads dynamicly by itself for my opinion.
Best reggards.

**Comment by davidcetinkaya** [comment]
Hello Leo (@Hahlh),

No worries. Just let me know when you have time to investigate this further 👍. You shouldn't have to force a **reInit** with Embla. As mentioned before, I need more details in order to help you.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hi Leo (@Hahlh),

Just wanted to ask if you have any updates on this?

Cheers,
David

**Comment by Hahlh** [comment]
I had to squeeze a project in. 
It's awesome of you, that you ask, David! :)

Tomorrow I will have a thorough look at it and report back.

Thank you for your support!

**Comment by Hahlh** [comment]
Okay @davidcetinkaya .

I have stripped down and ripped out everything from the component (styles, unrelated code, ..) as I believe it to be likely that I am causing the problem in the setup / useEffects through simple mistakes, so that a render is not triggered on page change.

That means, that this code is meant for you to be easily graspable at a glance, almost like pseudo code, but won't really work for copy & pasting it somewhere to run it. 

**If you don't spot the error on a first glance or simply prefer something to run, please tell me and I will create a clean version within codesandbox.**  

Here it is:

```
import React, { useState, useEffect, useCallback } from "react"
import { useEmblaCarousel } from "embla-carousel/react"
// import { PrevButton, NextButton } from "./EmblaCarouselButtons";


const viewportCss = {
  overflow: "hidden",
}
const containerCss = {
  display: "flex",
}
const slideCss = {
  position: "relative",
  minWidth: "100%",
}

export const ProductPresentationPlug = ({
  data,
  fragmentData,
}) =>
  {
    // Embla Setup
    const [viewportRef, embla] = useEmblaCarousel({
      loop: true,
      draggable: true,
    })

    const [prevBtnEnabled, setPrevBtnEnabled] = useState(false)
    const [nextBtnEnabled, setNextBtnEnabled] = useState(false)
    const [currentSnap, setCurrentSnap] = useState(0)
    const [numberOfSnaps, setNumberOfSnaps] = useState(0)

    const scrollPrev = useCallback(() => {
      setCurrentSnap(() => embla.selectedScrollSnap())
      // embla.reInit()
      return embla && embla.scrollPrev()
    }, [embla])

    const scrollNext = useCallback(() => {
      setCurrentSnap(() => embla.selectedScrollSnap())
      // embla.reInit()
      return embla && embla.scrollNext()
    }, [embla])

    const onSelect = useCallback(() => {
      if (!embla) return
      setPrevBtnEnabled(embla.canScrollPrev())
      setNextBtnEnabled(embla.canScrollNext())
    }, [embla])

    useEffect(() => {
      if (!embla) return
      setCurrentSnap(() => embla.selectedScrollSnap())
      setPrevBtnEnabled(() => embla.canScrollPrev())
      setNextBtnEnabled(() => embla.canScrollNext())
    }, [])

    useEffect(() => {
      if (!embla) return
      setNumberOfSnaps(() => embla.scrollSnapList().length)
    }, [embla])

    useEffect(() => {
      if (!embla) return
      embla.on("select", onSelect)
      onSelect()
    }, [embla, onSelect])
    // Embla Setup End

    const imagesJSX = images.map(item => {
      return (
        <div
          key={item._key}
          style={slideCss}
        >
          <SanityImage />
        </div>
      )
    })

    return (
      <>
        <div>
          <div>
            {/* Embla Carousel */}
            <div
              className={`overflow-hidden`}
              style={viewportCss}
              ref={viewportRef}
            >
              <div>{imagesJSX}</div>
            </div>

            <div className="">
              <button
                // disabled={!prevBtnEnabled}
                onClick={scrollPrev}
              >
                <svg />
              </button>
              <div>
                {currentSnap + 1} <span>/</span>{" "}
                {numberOfSnaps}
              </div>
              <button
                // disabled={!nextBtnEnabled}
                onClick={scrollNext}
              >
                <svg />
              </button>
            </div>
          </div>
        </div>
      </>
    )
  }
```

**Comment by davidcetinkaya** [comment]
Hi Leo (@Hahlh),

I took the liberty to add syntax highlighting to your code, I hope that's ok 🙂.  At this point I don't have a clear picture of the issue you're experiencing. You're mentioning that Embla is loosing slides. Does that mean that your carousel is global (meaning that it doesn't unmount when you navigate to another route)? Is it placed inside the Gatsby `Layout` component?

Looking at the code, you can change it a bit to make it shorter:

### Before
```jsx
const scrollPrev = useCallback(() => {
  setCurrentSnap(() => embla.selectedScrollSnap())
  // embla.reInit()
  return embla && embla.scrollPrev()
}, [embla])

const scrollNext = useCallback(() => {
  setCurrentSnap(() => embla.selectedScrollSnap())
  // embla.reInit()
  return embla && embla.scrollNext()
}, [embla])

const onSelect = useCallback(() => {
  if (!embla) return
  setPrevBtnEnabled(embla.canScrollPrev())
  setNextBtnEnabled(embla.canScrollNext())
}, [embla])

useEffect(() => {
  if (!embla) return
  setCurrentSnap(() => embla.selectedScrollSnap())
  setPrevBtnEnabled(() => embla.canScrollPrev())
  setNextBtnEnabled(() => embla.canScrollNext())
}, [])

useEffect(() => {
  if (!embla) return
  setNumberOfSnaps(() => embla.scrollSnapList().length)
}, [embla])

useEffect(() => {
  if (!embla) return
  embla.on("select", onSelect)
  onSelect()
}, [embla, onSelect])
```

### After
```jsx
const scrollPrev = useCallback(() => embla && embla.scrollPrev(), [embla])
const scrollNext = useCallback(() => embla && embla.scrollNext(), [embla])

const onSelect = useCallback(() => {
  if (!embla) return
  setPrevBtnEnabled(embla.canScrollPrev())
  setNextBtnEnabled(embla.canScrollNext())
  setCurrentSnap(embla.selectedScrollSnap())
}, [embla])

useEffect(() => {
  if (!embla) return
  setNumberOfSnaps(embla.scrollSnapList().length)
  embla.on("select", onSelect)
  onSelect()
}, [embla, onSelect])
```

There's no need to `setCurrentSnap` manually in your `scrollPrev` and `scrollNext` functions or anywhere else. Just add it to `onSelect` which is automatically called when Embla fires the `select` event in this piece of code:

```js
embla.on("select", onSelect)
```

Another thing I noticed is that your HTML and CSS setup for the carousel doesn't seem to be correct:

```jsx
<div
  className={`overflow-hidden`}
  style={viewportCss}
  ref={viewportRef}
>
  <div>{imagesJSX}</div> {/* This div is missing the required container styles? */}
</div>
```

According to the [docs](https://www.embla-carousel.com/get-started/react/#the-component-structure), you should have the following structure:

```jsx
import React from 'react'
import { useEmblaCarousel } from 'embla-carousel/react'

const EmblaCarousel = () => {
  const [emblaRef] = useEmblaCarousel()

  return (
    <div className="embla" ref={emblaRef}>
      <div className="embla__container">
        <div className="embla__slide">Slide 1</div>
        <div className="embla__slide">Slide 2</div>
        <div className="embla__slide">Slide 3</div>
      </div>
    </div>
  )
}

export default EmblaCarousel
```

...and the minimum required CSS for that should be:

```css
.embla {
  overflow: hidden;
}
.embla__container {
  display: flex;
}
.embla__slide {
  position: relative;
  flex: 0 0 100%; /* Change 100% to any slide size you want */
}
```

I also had troubles figuring out where the `images` variable comes from?

```jsx
const imagesJSX = images.map(item => {
  return (
    <div
      key={item._key}
      style={slideCss}
    >
      <SanityImage />
    </div>
  )
})
```

So what I would like to mention is that if you're passing the `images` variable as a prop to the carousel, Embla won't pick up any changes automatically if that prop changes. So you need to do something along these lines to tell Embla that the slide count changed:

```jsx
useEffect(() => {
  if (!embla) return
  if (embla.slideNodes().length !== images.length) { 
    embla.reInit() // Make Embla pick up changes in slide count
  }
}, [embla, images])
```

Let me know how it goes.

Best,
David

**Comment by Hahlh** [comment]
Thank you for thorough comment, David!

Adding syntax highlighting was definitely okay! :slightly_smiling_face:  
Reminds me to use it more consistently in comments.

I should have been a little clearer with the 'loosing slides' part.
You should be able to see the empty node list at minute 1 in the video of the first post. 
It could also be, that I am just misinterpreting, what kind of content it should contain in a functioning state and what information of the object I can actually rely on for debugging.

The component is a child of component that gets dynamically added to all product pages, so it should unmount on route change.
`productPage (template) > list of added modules for the specific page comes down from the CMS > among them productPresentationPlug which contains embla and is linked to the associated data.`

Thank you as well for the refactoring. Your code is much more concise.

Your points:
1. No need to setCurrentSnap manually
2. Invalid CSS
3. Origin of the images variable

Regarding 1.:
---
I am using the currentSnap state for outputting the current active slide number:
![image](https://user-images.githubusercontent.com/45669613/112530030-42383700-8da6-11eb-9ce9-046c378370a7.png)
This should also be possible through embla directly and I am not quite sure anymore, why I decided to not go that route.
Possibly it was, because the current issue prevented this from functioning correctly and I had to develop a temporary functioning approach for a presentation (really really unrealistic deadlines -> 16+ hours days). 

Regarding 2.:
---
I use Tailwind and I stripped out almost everything that would make it harder for you to read the logic. A little bit a gambit, as it presumed, that it would be easier for you to simply look at the code and easily spot the fault, than run and debug it. So basically assuming a rookie error by myself.

The needed classes were there and shouldn't be part of the problem, as displaying also seems to work fine before a route change.

Regarding 3.:
---
The images comes as a array down from a CMS (sanity). The available images should not change within a specific page, but I assume, that React not unmounting the component as it is reused on the next page could trigger that issue? That's easy to check though. 

I will also check whether your workaround works, simplify the code and post the complete component without anything stripped out, if the problem still persists (I hope you are fine with tons of CSS-in-JS :sweat_smile:). If it's solved, I will report back with the solution for the benefit of future generations :+1:


On a side note:
Did you update the docs?
I remember them to be good, but they are on a whole new level now? Or is that just me and little sleep looking at them last time? 


Thank you again, David!

**Comment by davidcetinkaya** [comment]
Hi Leo (@Hahlh),

Thank you for your response and explaining further. That sounds like a plan, try this:

```jsx
useEffect(() => {
  if (embla && embla.slideNodes().length !== images.length) { 
    embla.reInit() // Make Embla pick up changes in slide count
  }
}, [embla, images])
```

...and let me know if it helps.

### About the side note

> Did you update the docs?
I remember them to be good, but they are on a whole new level now? Or is that just me and little sleep looking at them last time?

I did. The previous documentation website was something I hacked together in a day or so. I didn't have much time so I used Create React App and hard coded everything including the content, just to give Embla users something to start with.

I created the new documentation website from scratch using **GatsbyJs**. Thanks to a some donations from some of my users, I was able to spend some real quality time with it. So I decided to improve both the visual looks and build a conventional documentation website. All content is written in Markdown which makes it really easy to edit and create new content.
I'm hoping to get more time soon to add more content under the [Guides](https://www.embla-carousel.com/guides/) section, that shows users how to achieve specific goals. I hope you like it.

Cheers!
David

**Comment by davidcetinkaya** [comment]
Hi again Leo (@Hahlh),

Just wanted to mention that I added a new [guide](https://www.embla-carousel.com/guides/add-and-remove-slides/#add-and-remove-slides-with-react) to the docs that demonstrates how to pick up changes in slides. It's pretty much the same approach I mentioned in my earlier [comment](https://github.com/davidcetinkaya/embla-carousel/issues/144#issuecomment-808475066).

Best,
David

**Comment by Hahlh** [comment]
Good morning David!

I have now implemented your refactoring. The code is now much cleaner and some additional problems vanished :)

I also implemented the `useEffect` you proposed, but unfortunately, this doesn't solve the issue of the slider not working on route change.

First I thought that that might be, because `if (embla && embla.slideNodes().length !== images.length)` would only trigger, if the slide counts would not be identical. It wouldn't trigger, if they were different slides but the same amount.
I tried to force a reinit using using `images.length + 5` which would mean that slide counts should always be different, but not no avail. 
Or should there be an intermittent state, where the slide count would be 0 and would therefore trigger the reinit?

My current guess is, that this relates to the same component for the slides being used on different pages.
The funny thing is, that embla is showing the correct first image on page change, but doesn't work with dragging or the arrows, although the number below changes, meaning that embla is working in the background without the slides updating?

Please excuse, that the feedback loop has been so slow so far. I am now able to devote much more time to this again and will be able to decrease the amount of time between answers significantly.

**Comment by Hahlh** [comment]
I can force it to update the slides, if I force an embla reinit on every render:
```javascript
useEffect(() => {
    if (embla) {
      embla.reInit() // Make Embla pick up changes in slide count
    }
  })
```

I can't force it to work, if I force an reinit on every mount:
```javascript
useEffect(() => {
    if (embla) {
      embla.reInit() // Make Embla pick up changes in slide count
    }
  }, [])
```

That should mean, that the component is indeed not unmounting, which could cause the problem.
I will investigate further.

**Comment by davidcetinkaya** [comment]
Hi Leo (@Hahlh),

Thank you for the additional information. It’s very hard to do any debugging without your exact setup. All I can say at this point is that you’ll have to manually initialize Embla when any prop or other state affecting the carousel changes, using a `useEffect`. Because if you’re slides and everything Embla needs are in place by the time you initialize or re-initialize Embla, everything will work as expected.

The last thing I can suggest without your setup available is to do this:

```jsx
useEffect(() => {
  if (embla) { 
    embla.reInit()
  }
}, [embla, slides])
```

This code will run as soon as anything related to the slides changes.

If you don’t have any luck with that, my suggestion is to create a CodeSandbox with the `gatsby-starter-template` they offer and reproduce the behavior there.

I hope this makes sense. 

Best,
David

**Comment by Hahlh** [comment]
I am already in the process of creating a codesandbox for reproduction and will also check whether your suggestion resolves the issue :+1:

**Comment by Hahlh** [comment]
[The CodeSandBox for reproduction.](https://codesandbox.io/s/gatsby-tailwindcss-embla-carousel-issue-144-reproduction-hkmw6)

Unfortunately I have so far failed to reproduce the issue in this environment.
I first speculated, that the source of the data could be the issue. Therefore I used the same JSON data source as in the CodeSandBox in the original project, but this still failed to resolve the issue.

This means that this issue is  likely unrelated to the component and embla itself and that it is likely caused by a parent. 
I will probably stumble over that issue as I clean up and optimize the project.

The temporary solution is to get the current `location`:
```javascript
import { globalHistory as history } from "@reach/router"
```
```javascript
const { location } = history
```

 and force a reinit on location change:
```javascript
useEffect(() => {
    if (embla) {
      embla.reInit()
    }
  }, [embla, location.pathname])
```
Hopefully that helps somebody in the future as they encounter a similar issue.

I will close this issue for now and thank you again for your incredible help, David! :pray:

**Comment by davidcetinkaya** [comment]
Thanks for the information Leo @Hahlh. I hope that you'll find what's causing this and if you do, let me know in this issue.

On a side note:
This is just a picky detail but you can import the location from reach router like so:

```js
import { useLocation } from '@reach/router'

const MyComponent = () => {
  const { pathname } = useLocation()
}
```

Cheers
David

**Comment by Hahlh** [comment]
Please keep those picky details coming :) 
Learning a lot from your code!

I will post, if I find a solution :+1:

**Comment by Hahlh** [comment]
Interestingly a hacky short term solution is to add an empty, invisible div without any dimensions as an additional child so every slide:

```javascript        
<div className="relative invisible w-0 h-0">.</div>
```

Does that give you any further clues about what could be going on?

**Comment by davidcetinkaya** [comment]
@Hahlh not really 😕. It sure sounds like a race condition going on. One additional thing you could try is to pass `null` instead of the `emblaRef` to the viewport until you have any slides:

```jsx
const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false })
const [hasSides, setHasSlides] = useState(false)

useEffect(() => {
  if (slides.length > 0) setHasSlides(true)
}, [slides, setHasSlides])

return (
  <div class="embla">
    <div class="embla__viewport" ref={hasSlides ? emblaRef : null}>
      ...
    </div>
  </div>
)
```

Another thing you could try is disabling the `gatsby-plugin-offline` if you have it installed. I remember that plugin was causing some issues for me. I never had the time to dig into the issue though.

Best,
David

**Comment by Hahlh** [comment]
@davidcetinkaya 

David! :)

I figured it out!

The culprit was an `items-center` (`align-items: center`) on a parent div of `embla`:
![image](https://user-images.githubusercontent.com/45669613/119723866-43e9ae00-be6e-11eb-895c-c1c8c746e933.png)


See also:

https://user-images.githubusercontent.com/45669613/119725293-11d94b80-be70-11eb-8b79-fa4c6e436543.mp4

I am not yet certain why though. Interesting for sure! How could this simple change make the loop, dragging and the position break?

**Comment by davidcetinkaya** [comment]
Hi Leo (@Hahlh),

Nice digging! Now that you have found the culprit, it all seems to make sense. I can’t tell for sure because I still don’t have access to your exact setup, but I think the issue is caused by `flex-col` and `items-center` used together. Because these will horizontally align the carousel. And my guess here is that Embla won’t be able to calculate the scroll snaps correctly when the carousel is aligned with CSS.

Embla has an [align option](https://www.embla-carousel.com/api/options/#align) that should be used to align the slides. Anyway, I’m happy to hear that you solved it 🙂.

**On a side note**
Be sure to check out the latest feature releases from 4.3.0 - 4.5.0. Maybe you’ll find some useful stuff there.

Cheers
David

**Comment by Hahlh** [comment]
Thanks, David :)

The interesting thing here is, that this is a parent of embla and shouldn't actually influence the working of the carousel, only its general position. And it is very strange in what way things break because of that (e.g. loop not working, no interactivity, ..) so it isn't only causing an issue with the positioning of the carousel. :+1: 

Even with the recommended base CSS, if this seemingly unrelated CSS would be used on a parent, it would break the carousel and would be quite hard to debug. 

After the 01.06, I will have a bit more time again and then I will try to finally reproduce the issue in a Codesandbox. That should also make it much easier for you to understand the underlying issue and decide, whether any things within embla should be adapted as a result.

I will check out all the new features for sure :slightly_smiling_face:  I am happy that you continue to work on embla and decided to only scale down public involvement. I hope that I will be able to use it for years to come and I am sure, that you will choose the right direction for it to move into.

All the best

Leo

**Comment by Hahlh** [comment]
Hey @davidjerleke !

How are you doing, how's life?

I am very happy to see that therer is lots of more momentum and versions for the project :slightly_smiling_face: 

I just stumbled issues, that could be related:

https://user-images.githubusercontent.com/45669613/172120179-8e0c0563-11f5-49b6-8998-3f47b96d987a.mp4

Setting flex on a parent seems to influence the carousel although nothing else changed. 
The carousel is filling up its half of the screen and should work as expected? It even does on the first render after `flex` is added to on of its parents.

Is this related or should I open up a new issue for this? 

As context, the carousel component:

```js

import { GatsbyImage } from "gatsby-plugin-image"
import React, { useState, useEffect, useCallback } from "react"

import useEmblaCarousel from "embla-carousel-react"
import { PrevButton, NextButton } from "./EmblaCarouselButtons"

const EmblaCarousel = ({ slides }) => {
  const [viewportRef, embla] = useEmblaCarousel({
    loop: true,
    skipSnaps: false,
  })
  const [prevBtnEnabled, setPrevBtnEnabled] = useState(false)
  const [nextBtnEnabled, setNextBtnEnabled] = useState(false)
  const [numberOfSnaps, setNumberOfSnaps] = useState(0)
  const [currentSnap, setCurrentSnap] = useState(0)

  const scrollPrev = useCallback(() => embla && embla.scrollPrev(), [embla])
  const scrollNext = useCallback(() => embla && embla.scrollNext(), [embla])

  const onSelect = useCallback(() => {
    if (!embla) return
    setCurrentSnap(embla.selectedScrollSnap())
    setPrevBtnEnabled(embla.canScrollPrev())
    setNextBtnEnabled(embla.canScrollNext())
  }, [embla])

  useEffect(() => {
    if (!embla) return
    embla.on("select", onSelect)
    onSelect()
    setNumberOfSnaps(embla.scrollSnapList().length)
  }, [numberOfSnaps, embla, onSelect])

  useEffect(() => {
    if (!embla) return
    embla.reInit({ startIndex: 0, loop: true, skipSnaps: true })
    setCurrentSnap(embla.selectedScrollSnap())
    setNumberOfSnaps(embla.scrollSnapList().length)
  }, [slides, setNumberOfSnaps, embla])

  return (
    <div className="relative embla">
      <div className="w-full overflow-hidden embla__viewport" ref={viewportRef}>
        <div className="flex items-center select-none embla__container touch-none">
          {slides.map(slide => (
            <div key={slide._key} className="relative min-w-full">
              <div className="relative h-full overflow-hidden">
                <GatsbyImage
                  className="h-120"
                  imgClassName="object-contain"
                  objectFit="contain"
                  objectPosition={"50% 50%"}
                  image={slide.asset.gatsbyImageData}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
      <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled} />
      <NextButton onClick={scrollNext} enabled={nextBtnEnabled} />
      <div className="absolute flex justify-center left-1/2 -translate-x-1/2 bottom-7.5 text-basePP md:text-lg md:mx-12 min-w-24">
        {currentSnap + 1} <span className="px-1 md:px-2">/</span>{" "}
        {numberOfSnaps}
      </div>
    </div>
  )
}

export default EmblaCarousel

```

`embla`, `embla__viewport`, and  `embla__container` are only used as structural markers and don't add any css. 

All the best,

Leo

**Comment by davidjerleke** [comment]
Hi Leo (@Hahlh),

I hope you’re doing great 🙂. This is caused by an incorrect setup. Embla has no known bugs related to items not aligning properly or similar. 

One problem is that you’re aligning items inside the `embla__container` (remove items-center). You shouldn’t align anything there with CSS because Embla will do it for you. Use the [align option](https://www.embla-carousel.com/api/options/#align) if you want to change slide alignment.

There might be additional things causing the problems you’re experiencing so please read the following guides:

- [Slide Container](https://www.embla-carousel.com/guides/slide-container/).
- And also the two other guides about Slide Sizes and Slide Gaps.

Beat,
David
