### ISSUE TITLE
`loop` doesn't work when displaying three slides out of four total slides

### ISSUE THREAD

**Issue by patrickhuang94** [davidcetinkaya/embla-carousel#149]
Hi,

When the total number of slides is set to 4, `slidesToShow: 3`, and `slidesToScroll: 1`, the `loop` option stops working. This was mentioned in the docs, which is probably what's happening

```
loop
... Automatically falls back to false if slide content isn't enough to loop.
```

This can be reproduced in the sandbox:
https://codesandbox.io/s/embla-carousel-loop-react-forked-7200i?file=/src/js/index.js

Two questions:
1. What's the reasoning for this restriction? There's definitely enough slide content to loop. I was expecting to see [1,2,3] on initial render, [2,3,4] on next click, and [3,4,1] on next click.
2. Is there a workaround for this?

Thanks,
Patrick

**Comment by davidcetinkaya** [comment]
Hello Patrick (@patrickhuang94),

Thank you for your question. The documentation is correct, Embla Carousel will check if there are enough slide content to make the loop effect work without any flickering (white space showing).

Now, assuming you have 4 slides, you would think that setting the CSS like this:

```css
.embla__slide {
  min-width: 33.33333%;
}

/* ...or a nicer way to put it */

.embla__slide {
  min-width: calc(100% / 3);
}
```

...would result in enough content to make the loop effect work. But this isn't the case. Because the viewport is 100%. And the slide content for 3 slides (we subtract 1 slide because it's needed to flip around for the loop effect to work) will be 33.33333 * 3 = 99.99999%. Additionally, when I log the slide sizes calculated from the boundingClientRect, the browser gives 33.331691216316074. Which isn't even 33.33333%.

I hope this explanation makes sense.

Best,
David

**Comment by patrickhuang94** [comment]
Great, thanks for the quick response and explanation! Cheers.

**Comment by davidcetinkaya** [comment]
Hi again Patrick (@patrickhuang94),

If you want to perform a check to know if slide content is enough to loop or not, there's an unofficial way of doing this:

```js
embla.dangerouslyGetEngine().slideLooper.canLoop();
```

Just in case you want to duplicate slides based on the **boolean** it returns.

I hope it helps.

Best,
David

**Comment by patrickhuang94** [comment]
Another solution that I just thought of, instead of duplicating slides:

Currently my code looks like this
```
<div className="embla__container">
    {children.map((slide, index) => (
        <div
            key={index}
            className="embla__slide"
            style={{
                minWidth: `${100 / slidesToShow}%`,
            }}
        >
            <div className="embla__slide__inner">{slide}</div>
        </div>
    ))}
</div>
```

which, whenever slidesToShow = 3, will resolve to 33.33 * 3 = 99.99% (and thus never hit the required 100%). I can probably add some custom logic that rounds the min width to `33.34%` whenever we receive a slidesToShow input of `3`

**Comment by davidcetinkaya** [comment]
Hi Patrick (@patrickhuang94),

Of course! You can solve this in different ways, but I guess the bottom line is that the library won’t do it for you 🙂. As I mentioned you can use the unofficial hint I demonstrated in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/149#issuecomment-789228871).

Did you solve it for your use case?

Kindly,
David

**Comment by davidcetinkaya** [comment]
@patrickhuang94 I'm closing this issue if you have no [objections](https://github.com/davidcetinkaya/embla-carousel/issues/149#issuecomment-789589918)?

**Comment by davidcetinkaya** [comment]
@patrickhuang94 I’m closing this as resolved. You’re welcome to open this issue again if you don’t agree.

Best,
David

**Comment by piotrgora** [comment]
this solution doesn't work

```const notEnoughToLoop = !embla.dangerouslyGetEngine().slideLooper.canLoop()

if (notEnoughToLoop) {
  // Duplicate your slides
  embla.reInit(); // Re-init embla to pick up all the slides including the duplicated ones
}```

**Comment by davidjerleke** [comment]
Hi @piotrgora,

Please refrain from just saying “This doesn’t work”. You’re not sharing a single piece of information or proof that supports your claim. As mentioned [here](https://github.com/davidjerleke/embla-carousel/issues/149#issuecomment-789589918):

> the bottom line is that the library won’t do it for you, if you’re looking to make your carousel loop even if the slide content isn’t enough

Of course [this doesn’t work](https://github.com/davidjerleke/embla-carousel/issues/149#issuecomment-789228871)  right off the bat, you have to replace the comment in that piece of code with actual code that duplicates your slides.

**Comment by piotrgora** [comment]
Hello @davidjerleke,

it was late and after this comment I understood that `reInit` will duplicate the slider elements itself (don't know why I thought that, but I must have misunderstood the comment above reInit )

I wrote my library using the `canLopp()` information and everything works fine. 

Could you change the text from "Duplicate your slides" to something similar to "Write code/function here that will duplicate slider elements". 

I didn't read the whole thread and missed the information you quoted.

Sorry and thanks for the quick reply!

**Comment by davidjerleke** [comment]
Hi @piotrgora,

> Could you change the text from "Duplicate your slides" to something similar to "Write code/function here that will duplicate slider elements" and change dangerouslyGetEngine() to internalEngine()?

Thanks for the constructive feedback. I've updated the code snippet and the comment now 🙂. 

> I wrote my library using the canLoop() method and everything works fine.

Glad to hear that you solved it 🎉.

>I didn't read the whole thread and missed the information you quoted.

> Sorry and thanks for the quick reply! 

No worries! I hope I didn't come across as rude. My only intention was to convey that I was missing crucial information to understand you.

Best,
David
