### ISSUE TITLE
Change options at breakpoints

### ISSUE THREAD

**Issue by lorenzecode** [davidcetinkaya/embla-carousel#150]
Hi David

could you help me with some example to change options at breakpoints, i need to change the draggable to false, in min-width 1024px

I'm looking for an example and haven't found it, I'm using vanilla js

thank you so much

**Comment by davidcetinkaya** [comment]
Hi @lorenzecode,

Thank you for your question. Try something along these lines:

```js
const BREAKPOINT = 1024

embla.on('resize', () => {
  const draggable = window.innerWidth < BREAKPOINT
  embla.reInit({ draggable })
})
```

Let me know if it helps.

Best,
David

**Comment by lorenzecode** [comment]
Thanks for answering

it worked, but when I start at the breach point 1024, the draggable is active and only changes if I resize

**Comment by davidcetinkaya** [comment]
That's because you need to run the same function upon init:

```js
const BREAKPOINT = 1024

// Check for the window size when you initialize your carousel too
const options = { draggable: window.innerWidth < BREAKPOINT }
const embla = EmblaCarousel(emblaNode, options)

embla.on('resize', () => {
  const draggable = window.innerWidth < BREAKPOINT
  embla.reInit({ draggable })
})
```

Kindly,
David

**Comment by lorenzecode** [comment]
Wow,

It Works Very Well, Thank You!

For the other options would it be the same?

Ex: Align: Start for the Center

**Comment by davidcetinkaya** [comment]
> For the other options would it be the same?

Yes, the same approach will work for other options as well.

Enjoy,
David

**Comment by davidcetinkaya** [comment]
@lorenzecode it’s now possible to change options at breakpoints using [this approach](https://www.embla-carousel.com/guides/breakpoints/#changing-options).

Best,
David
