### ISSUE TITLE
Feature request: more scroll physics

### ISSUE THREAD

**Issue by jeiea** [davidcetinkaya/embla-carousel#163]
### Feature request is related to
- [x] The Embla Carousel core (all versions)

###  Is your feature request related to an issue?
I'm curious whether embla-carousel has an option like [`ClampingScrollPhysics`](https://api.flutter.dev/flutter/widgets/ClampingScrollPhysics-class.html). It seems all examples have bouncing scroll physics at both ends of the contents. 

###  Describe the solution you'd like
Add terminalPhysics enum option that can be 'clamp', 'bounce', etc.

### Describe alternatives you've considered
I have no better idea about api.

**Comment by davidcetinkaya** [comment]
Hi @jeiea,

Thank you for your feature request. Would you agree that this request is more or less a **duplicate** of #42?

Kindly,
David

**Comment by davidcetinkaya** [comment]
Thanks for confirming. Let's continue the discussion in issue #42 @jeiea.

**Comment by davidcetinkaya** [comment]
Duplicate of #42.
