### ISSUE TITLE
Error when scrolling between slides by dragging

### ISSUE THREAD

**Issue by EctordAniel** [davidcetinkaya/embla-carousel#170]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [x] The Embla Carousel core (all versions)
- [x] Documentation website
- [ ] Other

### Embla Carousel version

- v4.3.1

### Describe the bug

- When you arrive by dragging to the last slide, the selectedIndex returns to the beginning, to 0, you must drag again to take the index of the last slide.
It only happens when scrolling by dragging the slides..
Attach the link of the web page since I realized that the same error occurs there, 
I solved it by downgrade version to 4.0.6.

### CodeSandbox

- https://www.embla-carousel.com/examples/navigation/.

### Steps to reproduce

1. Go to 'Examples'
2. Click on 'Navigation'
3. Drag to the last slide on 'Arrows and Dots'

### Expected behavior

- That takes the correct slide index.

### Additional context

- Penultimate slide:
![image](https://user-images.githubusercontent.com/57757074/113489573-fb77ca80-9492-11eb-8acf-59e72008aeb5.png).
- Last slide:
![image](https://user-images.githubusercontent.com/57757074/113489625-41cd2980-9493-11eb-94e1-a2f34a5a85e7.png)
- Expected:
![image](https://user-images.githubusercontent.com/57757074/113489651-72ad5e80-9493-11eb-9317-d102c6bcc84b.png)

**Comment by davidcetinkaya** [comment]
Hi @EctordAniel,

I can confirm that this is a bug with v4.3.1. Looking at the code, I can see why this is happening. I will release a patch version with a fix for this bug as soon as possible.

I’ll let you know when I’ve released v4.3.2 with the fix. Thank you for your patience.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi Hectór (@EctordAniel),

I've released [v4.3.2](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.3.2) which includes a fix for this issue. Try it out if you don't mind.

Thank you for creating this issue.

Cheers,
David

**Comment by EctordAniel** [comment]
Thanks David. Ok, i'll tried.
