### ISSUE TITLE
Exposing default options

### ISSUE THREAD

**Issue by nikrowell** [davidcetinkaya/embla-carousel#175]
### Feature request is related to

The Embla Carousel core (all versions)

### Describe the solution you'd like

Hi David (@davidcetinkaya),

Love seeing all the traction Embla Carousel is getting! One thing I've found myself doing frequently is creating a default options object on Embla for use with different carousel instances. For example:

_entry or initialization file_
```js
import Embla from 'embla-carousel';

Embla.defaults = {
  loop: true,
  draggableClass: 'cursor-grab',
  draggingClass: 'cursor-grabbing',
};
```
_component file_
```js
const carousel = Embla(node, {
  ...Embla.defaults,
  loop: false
});
```

### Additional context

Idea initially came from an undocumented [Flickity feature](https://github.com/metafizzy/flickity/issues/115). How do you feel about adding something like this? Would be happy to PR if you'd like (though haven't looked at the codebase in a long time 😆)

**Comment by davidcetinkaya** [comment]
Hi Nik (@nikrowell),

Thank you for your feature request. How about exporting the `defaultOptions` object instead of attaching it to the `EmblaCarousel` instance initializer?

Usage would look like this:

```js
// Grab default options
import EmblaCarousel, { defaultOptions } from 'embla-carousel'

// Create your defaults
export const carouselDefaultOptions = {
  ...defaultOptions,
  loop: true,
  draggableClass: 'cursor-grab',
  draggingClass: 'cursor-grabbing',
}

// Create your instance
const carousel = EmblaCarousel(emblaNode, {
  ...carouselDefaultOptions,
  loop: false
})
```

I'm thinking that it might be a good idea to not mutate the `EmblaCarousel` instance initializer. Note that I'm aware that there might be better names than `defaultOptions`, so please suggest a different name if you have one in mind 🙂.

Let me know what you think.

Best,
David

**Comment by nikrowell** [comment]
@davidcetinkaya Makes sense on not wanting to mutate... I'm fine with closing this and continuing to use my approach if I need it, just remembered of the Flickity example and thought I'd throw it out there. 

Thanks for being so responsive with everything!

**Comment by davidcetinkaya** [comment]
@nikrowell, out of curiosity: Do you think my suggestion doesn't add any value when compared to how you've solved this up until now? Do you prefer your initial suggestion over mine?

Best,
David

**Comment by nikrowell** [comment]
@davidcetinkaya I probably prefer the initial approach, mostly because the `defaultOptions` didn't reduce any boilerplate. One of the biggest selling points with Embla for me is how lightweight and extensible it is, so omitting features and leaving things like this up to the user is fine with me 😀

**Comment by davidcetinkaya** [comment]
@nikrowell thank you for your response.

I was just curious so I hope you don’t mind me asking. Please note that I’m almost always open to discussing things, even when my initial response differs from the suggested feature 🙂.

Best,
David

**Comment by davidcetinkaya** [comment]
Closing this @nikrowell. Feel free to open it again if you want to discuss this further!

Best,
David

**Comment by davidcetinkaya** [comment]
Hi @nikrowell,

I hope you're doing great 🙂. I'm considering adding this feature to the Embla core. The way I understand this feature (and correct me if I'm wrong), is that it offers a more convenient way to set **default options** for your carousels. Considering your suggestion:

_entry or initialization file_
```js
import EmblaCarousel from 'embla-carousel';

EmblaCarousel.defaultOptions = { loop: true };
```
_component file_
```js
const carousel = EmblaCarousel(node, {
  ...EmblaCarousel.defaultOptions,
  align: 'start'
});
```

...I think there's even a more convenient way of achieving this.

_entry or initialization file_
```js
import EmblaCarousel from 'embla-carousel';

EmblaCarousel.defaultOptions = { loop: true };
```
_component file_
```js
const carousel = EmblaCarousel(node, { align: 'start' });
```

...the main difference being is that setting the default options will affect all carousels you initialize. Additionally, I would like to add this feature so it's useful for React users too. How would we go about this? Do you have any ideas? Does the following solution make sense?

```jsx
import useEmblaCarousel, { EmblaCarousel } from 'embla-carousel-react';

EmblaCarousel.defaultOptions = { loop: true };

export const Carousel = () => {
  const [emblaRef] = useEmblaCarousel({ align: 'start' })

  return (
    <div className="embla" ref={emblaRef}>
      <div className="embla__container">
        <div className="embla__slide">Slide 1</div>
        <div className="embla__slide">Slide 2</div>
        <div className="embla__slide">Slide 3</div>
      </div>
    </div>
  )
}
```

I look forward to your response and thank you for your time!

Cheers,
David

**Comment by nikrowell** [comment]
Hi @davidcetinkaya - 

Thanks for thinking of me on this 😀 I definitely like the idea of setting defaults without the need to spread them into each instance. Would also be nice if this worked for plugins - could see `ClassNames` being handy here. 

I mostly use the vanilla version of Embla, so I may not have much to add on the React side. What you're proposing looks good to me though and is consistent with how it would (potentially) work in Embla core.

**Comment by davidcetinkaya** [comment]
Thank you for the input @nikrowell 🙂. I think it’s a great idea that plugins should work with default options too. I’ll let you know when I have something.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi @nikrowell,

This feature has been released with [v.6.2.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.2.0) 🎉. Please read more about it in the docs:

- [Global carousel options](https://www.embla-carousel.com/api/options/#global-options)
- [Global plugin options](https://www.embla-carousel.com/api/plugins/#options)

Give it a try if you want.

Best,
David

**Comment by nikrowell** [comment]
@davidcetinkaya awesome!
Thanks for all your continued work on improving Embla while keeping it lightweight and flexible etc 😀 

Side note - your commitment to answering questions and helping others make the most out of Embla doesn't go unnoticed. Happy to help in any way I can (I definitely need to spend more time familiarizing myself with the underlying engine!).

Cheers!
