### ISSUE TITLE
Is there a way to know which direction the slider moved?

### ISSUE THREAD

**Issue by m-bp** [davidcetinkaya/embla-carousel#179]
Say for example that you have a slider with 2 slides and loop enabled.

If I am listening to the `select` event I can see the new index and the old index for the slides... But I have no way of knowing if I went from slide 1 to slide 2 by going back or forward, do I?

**Comment by davidcetinkaya** [comment]
Hi Mario (@m-bp),

Thank you for your question. No, not with the current API. If you really need to know this, there’s an unofficial way to do it:

```js
embla.on('select', () => {
  const direction = embla.dangerouslyGetEngine().scrollBody.direction()
  console.log(direction)
})
```

This will return either **1** which means **backward** or **-1** which means **forward**.

But please **note** that getting the direction when the select event is triggered, only tells you which direction the carousel is heading at the moment the event is triggered. The user may start dragging the carousel and change the direction before the carousel has reached its destination.

Let me know if it helps.

Best,
David

**Comment by m-bp** [comment]
> But please note that getting the direction when the select event is triggered, only tells you which direction the carousel is heading at the moment the event is triggered. The user may start dragging the carousel and change the direction before the carousel has reached its destination.

Gave it a go but because of that very quirk you mention it's not going to work for me. Too many false positives.

Basically I want to trigger an analytics event whenever someone uses the slider and I want to know if they slide forward or backwards but it doesn't seem possible unless I ignore drags and I just listen to arrow clicks instead.

**Comment by davidcetinkaya** [comment]
Hi again Mario (@m-bp),

> Gave it a go but because of that very quirk you mention it's not going to work for me. Too many false positives.

I'm not sure if I'm understanding you correctly. Any carousel, whether it's Embla or another library can change direction before actually reaching its destination?

I think you need to specify your requirement further in order for me to be able to provide a solution.

Kindly,
David

**Comment by m-bp** [comment]
I tested the code snippet ('select' event listener) you gave me and the result was the following:

* Dragging to the left logs -1
* Dragging to the right logs 1
* Next button logs -1
* Back button logs 1

Dragging works flawlessly. However:

* Next button (logs -1) then Back button before it settles would log -1 again.
* Back button (logs 1) then Next button before it settles would log 1 again.

This makes no sense as it is now moving the opposite way.

The buttons simply call scrollNext/scrollPrev on click.

**Comment by davidcetinkaya** [comment]
> However:
>
> - Next button (logs -1) then Back button before it settles would log -1 again.
> - Back button (logs 1) then Next button before it settles would log 1 again.
> This makes no sense as it is now moving the opposite way.

I see. This is because the `select` event fires before it actually starts scrolling to its destination, when you trigger scrollNext/scrollPrev with the arrows. So what you're getting is the direction the carousel was moving before the click.

One alternative is to add an `afterSelect` event to the Embla Carousel core. But if you need to get this working now you try the following:

```js
embla.on("pointerUp", () => {
  const direction = embla.dangerouslyGetEngine().scrollBody.direction();
  console.log(direction);
});

const myScrollNextWrapper = () => {
  console.log(-1) // Set -1 as direction here
  embla.scrollNext()
}

const myScrollPrevWrapper = () => {
  console.log(-1) // Set -1 as direction here
  embla.scrollNext()
}
```

**Comment by davidcetinkaya** [comment]
@m-bp, let me know how it goes when you've had the time to try it out.

**Comment by davidcetinkaya** [comment]
Hi Mario (@m-bp),

I'm closing this issue for now. You may reopen this issue if you want to discuss this further or would like to suggest a feature related to this.

Best,
David
