### ISSUE TITLE
Option to reduce the snap speed

### ISSUE THREAD

**Issue by akardet** [davidcetinkaya/embla-carousel#181]
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [x] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Is your feature request related to an issue?

I was formerly on v4.3.0 and jumped up to v4.5.0 to start using the skipSnaps option, but noticed that the carousel snaps to the slide quicker than it did in v4.3.0. It snaps a little too quick for my app.

You can flip between v4.5 and v4.3 and notice the difference
[CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-38-forked-t4xgt?file=/src/js/EmblaCarousel.js)

### Describe the solution you'd like

A way to modify the drag force to feel more like v4.3

### Describe alternatives you've considered

Is there a value I could modify from the `dangerouslyGetEngine()` function?

**Comment by davidcetinkaya** [comment]
Hi Sam (@akardet),

Did you try the latest version on a desktop?

Best,
David

**Comment by akardet** [comment]
Feels different for both desktop and on a touch device.

**Comment by davidcetinkaya** [comment]
I think the change in speed for touch devices turned out to be better. But I think we could lower the speed when dragging with a mouse. What’s your thoughts about this suggestion?

**Comment by akardet** [comment]
I won't make too much of a fuss about it if no one else has any strong opinions about it. It still functions great. Thanks for the reply.

**Comment by davidcetinkaya** [comment]
@akardet maybe some users prefer the previous speed (4.3.x and down). Let's see if this gets any traction. I'll take a look at this next week and maybe I'll lower the speed.

**Comment by davidcetinkaya** [comment]
Hi Sam (@akardet),

I've decided to slightly reduce the snap speed (not as much as it was before the v4.5.0 release though). I can't tell when but I'll let you know when I've had time to release it.

Best,
David

**Comment by davidcetinkaya** [comment]
Hello Sam (@akardet),

I've just released [v4.5.1](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.5.1) with a reduction of snap speed when dragging. Enjoy!

Best,
David

**Comment by akardet** [comment]
Hey David,

Finally got around to upgrading and testing out 4.5.1 and it's feeling great. Thank you for all your hard work!

**Comment by pm0u** [comment]
Is it possible to have this be customizable? That would be a great feature add!

**Comment by davidcetinkaya** [comment]
Hi Paul (@pm0u),

Thank you for your question. Have you read the [announcement](https://github.com/davidcetinkaya/embla-carousel/issues/187#issue-873669552)?

Cheers,
David

**Comment by NicoPom** [comment]
> Is it possible to have this be customizable? That would be a great feature add!

I second this :)

**Comment by ilyachase** [comment]
> Is it possible to have this be customizable? That would be a great feature add!

Agree, would be great. Was looking for this option.
