### ISSUE TITLE
Force to move the slides is too heigh on desktop

### ISSUE THREAD

**Issue by KonstantinSchuette** [davidcetinkaya/embla-carousel#182]
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [X] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Is your feature request related to an issue?

No

### Describe the solution you'd like
The slider is the first thing the visitors are seeing, when they visit my site. It stretches over the full width and height of the screen.

Now if a visitor has a desktop pc (e.g. 1920x1080) they need to drag the slide over the half of their screen, if they slide slowly, to move to the next slide. So they need to move their mouse very far, just to do the sliding.

Maybe it is possible to pass a value to the slider that sets the force heigher or lower.

**Comment by davidcetinkaya** [comment]
Hi Dewey (@KonstantinSchuette),

Would you mind sharing a video of the behavior you're describing?

Thank you in advance.

Best,
David
