### ISSUE TITLE
Weird behavior with loop option

### ISSUE THREAD

**Issue by jeiea** [davidcetinkaya/embla-carousel#185]
### Issue is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.1

### Describe the issue

I did not expect picture disappearance at the end.

https://user-images.githubusercontent.com/4188984/116530636-372e7480-a919-11eb-9612-1685f7aee0d6.mov

### CodeSandbox

https://codesandbox.io/s/embla-carousel-variablewidths-react-forked-n4ku3?file=/src/js/EmblaCarousel.js

### Steps to reproduce

1. Open the above codesandbox
2. Scroll over the 10th slide.

### Expected behavior

Pictures should appear naturally.

**Comment by davidcetinkaya** [comment]
Hi @jeiea,

Thank you for your issue. This is **not a bug** with the Embla Carousel core. Loop is working fine. I would suggest you to check the parallax [CodeSandbox](https://codesandbox.io/s/embla-carousel-parallax-react-ep71f) out because it's quite similar to what you want to achieve. The parallax example is working with `loop: true`.

Kindly,
David

**Comment by jeiea** [comment]
Thanks for the reference. It really helps.

**Comment by davidcetinkaya** [comment]
@jeiea let me know how it goes. If you get it working we can put that example on the documentation website.

**Comment by jeiea** [comment]
https://codesandbox.io/s/embla-carousel-variablewidths-react-forked-qp4et?file=/src/js/EmblaCarousel.js

I can't sure whether this can be an interesting example, but I share it anyway.

Commented lines may be useful for vanilla one.

I saw the announcement today. I'm afraid it is discontinued but I also know the efforts so far is admirable.

**Comment by davidcetinkaya** [comment]
Cool @jeiea,

Thank you for sharing. That looks really cool! I'll add this to the docs whenever I have time. 

Best,
David

**Comment by davidcetinkaya** [comment]
Hi @jeiea,

I just added a [**scale carousel**](https://www.embla-carousel.com/examples/inspiration/#scale) to the examples page. I used your [setup here](https://github.com/davidcetinkaya/embla-carousel/issues/185#issuecomment-831284850) as a starting point so thank you for that.

I added two things:

- Only slides in view will be animated.
- Although this might not be a common use case, I added support so you can have as many slides as you wish visible in the viewport (in contrast to 3 in your example).

Let me know what you think.

Best,
David

**Comment by jeiea** [comment]
I'm glad it helped your inspiration for documentation material.
