### ISSUE TITLE
Conditional rendering?

### ISSUE THREAD

**Issue by simplenotezy** [davidcetinkaya/embla-carousel#188]
In some circumstances I use the same component, and that component has a prop for whether or not it should be a carousel/slider.

So since it's not possible to load hooks conditionally, I wondered if there was another workaround to prevent embla carousel from initiating? Like giving it `null` as options or similar.

**Comment by davidcetinkaya** [comment]
@simplenotezy, pass `null` instead of the `emblaRef` until you want to initialize Embla. Embla will watch the `emblaRef` for changes so that should work.

**Comment by simplenotezy** [comment]
That's smart, and a good approach. This is most likely the most enjoyable carousel library I have every played around with. A pure pleasure to work with, just wanted you to know that! ;)

**Comment by Hahlh** [comment]
> That's smart, and a good approach. This is most likely the most enjoyable carousel library I have every played around with. A pure pleasure to work with, just wanted you to know that! ;)

Can't agree enough!
