### ISSUE TITLE
Not loading for Googlebot smartphone

### ISSUE THREAD

**Issue by apo-fw** [davidcetinkaya/embla-carousel#191]
Thanks for the pretty neat plugin :) 
Library returning 403 when being loaded by GoogleBot Smartphone:
![image](https://user-images.githubusercontent.com/69133271/119293369-7c299a80-bc7c-11eb-9715-896c9994a5cf.png)

**Comment by davidcetinkaya** [comment]
Hi @apo-fw,

Thank you for your issue. This is the `unpkg` servers returning a `403`. I'm not sure why you think this is an issue with the library itself? Because pasting the link into the browser is working as expected.

Try `jsdelivr` and see if that works:

```html
<script src="https://cdn.jsdelivr.net/npm/embla-carousel@4.5.2/embla-carousel.umd.min.js"></script>
```

Kindly,
David

**Comment by apo-fw** [comment]
Oh thank you, that works! My mistake, I didnt try a different server.

**Comment by davidcetinkaya** [comment]
@apo-fw glad to hear that it works 👍. I'm not sure why `unpkg` is returning `403` for Googlebot smartphone. But I still don't think this is an issue with the library itself, but rather with `unpkg` or `Googlebot smartphone` 🙂.

Enjoy!
David
