### ISSUE TITLE
Broken layout when add new items to picker

### ISSUE THREAD

**Issue by nvuhung** [davidcetinkaya/embla-carousel#200]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.3

### Describe the bug

I use your picker example and add new items after render, but the layout is broken

### CodeSandbox
I have cloned [your example](https://codesandbox.io/s/embla-carousel-ios-picker-default-react-fotej?file=/src/js/index.js):

- https://u8v3f.csb.app/

### Steps to reproduce

1. Go to CodeSandbox
2. See the picker work well
3. I use interval to add new item each 3 seconds
4. Broken layout

### Expected behavior

- The picker should keep active index and the layout is not broken if I have new items

### Additional context

Please help me check some cases: 
- Add new items
- Add new item and update selected index same time
- 1 more thing, please help me if possible, I want to remove the radius of picker, so I can have the UI like below:

![image](https://user-images.githubusercontent.com/11483168/121875928-31f38080-cd33-11eb-9f75-ade2a2b6583e.png)

Btw, I very like your library, It's great 👏

**Comment by davidcetinkaya** [comment]
Hi @nvuhung,

Thank you for your question. This is not a bug. If you don't want the radius of the pickers, you can just use three basic Embla Carousels with the `axis` option set to `y` like in this [CodeSandbox](https://codesandbox.io/s/embla-carousel-ios-picker-default-react-forked-5ryy4) example.

I would also suggest that you read [this guide](https://www.embla-carousel.com/guides/add-and-remove-slides/#add-and-remove-slides-with-react) in the docs to get a better understanding of how to add/remove slides properly.

I hope this helps.

Best,
David
