### ISSUE TITLE
Can't get Embla Carousel working in a Modal (Here I use Rodal as Modal)

### ISSUE THREAD

**Issue by siamahnaf198** [davidcetinkaya/embla-carousel#210]
When I use embla in my page it run successfully. But when I put it in a modal it can't run the slider. Then I can't slide the item. Here is some image.
![Screenshot 2021-08-23 174434](https://user-images.githubusercontent.com/78312010/130441795-79e352d3-8869-4703-acd3-a68850844db7.png)

<Rodal
                visible={state.visible}
                onClose={() => modaleToggler('hide')}
                width={950}
                height={580}
                customMaskStyles={{ background: '#0000009c' }}
                enterAnimation="zoom"
                leaveAnimation="slideDown"
            >
                <Heading>{name}</Heading>
                <Flex>
                    <Icons icon={icon} />
                    <Paragraph as="p">{details}</Paragraph>
                </Flex>
                <Carousels works={works} />
            </Rodal>

In Carousel Component I write this code-
function Carousels({ works }) {
    const [emblaRef] = useEmblaCarousel({ skipSnaps: false, draggable: true });

    return (
        <div ref={emblaRef} className="embla">
            <div className="embla__container">
                {works &&
                    works.map((work, i) => (
                        <div key={i} className="embla__slide">
                            <h1>{work.name}</h1>
                        </div>
                    ))
                }
            </div>
        </div>
    )
}
export default Carousels;

**Comment by davidcetinkaya** [comment]
Hi @siamahnaf198,

Thank you for your question. I'm not sure what you're suggesting? Embla has been around for some years now and it wouldn't make any sense at all if it couldn't run in a modal. I've used it in modals a lot. I think you might not be doing it right. When you open the modal the size of the modal probably changes, so you need to tell that to Embla by re-initializing it.

Try running `embla.reInit()` when the modal is opened.

David

**Comment by siamahnaf198** [comment]
Can you sent example code?

My Code is
import { useEffect } from 'react';
import { useEmblaCarousel } from 'embla-carousel/react';


function Carousels({ works, visible }) {
    const [emblaRef, embla] = useEmblaCarousel({ skipSnaps: false, draggable: true });

    useEffect(() => {
        if (embla && visible) embla.reInit();
    }, [embla, visible])
    return (
        <div ref={emblaRef} className={`embla ${visible ? 'active' : ''}`}>
            <div className="embla__container">
                {works &&
                    works.map((work, i) => (
                        <div key={i} className="embla__slide">
                            <h1>{work.name}</h1>
                        </div>
                    ))
                }
            </div>
        </div>
    )
}
export default Carousels;


Here visible return true when modal is open and return false when modal is close?

Please help me to solve it.

**Comment by davidcetinkaya** [comment]
Hi @siamahnaf198,

Please create a CodeSandbox that clearly demonstrates the issue and I’ll look into it when possible.

David

**Comment by siamahnaf198** [comment]
Hi @davidcetinkaya 

I create this code sendBox- https://codesandbox.io/s/heuristic-brattain-0yjb9?file=/pages/index.js

Carousel runs when I open inspect element. But when I reload or load the page it can't run. Please check the code and solve the problem.

Thank you David :)

**Comment by davidcetinkaya** [comment]
Hi @siamahnaf198,

The CodeSandbox doesn't work. Please fix the following error with the CodeSandbox and I'll look into it after that:

<img width="591" alt="build" src="https://user-images.githubusercontent.com/11529148/130578623-6d3c7f33-5413-4a15-9b25-cd87ee810ddf.png">

David

**Comment by siamahnaf198** [comment]
I didn't see any error.
![Screenshot 2021-08-24 141132](https://user-images.githubusercontent.com/78312010/130581688-36c61658-3b65-471f-8c6a-52b6561ab67c.png)

Please visit the link again- https://codesandbox.io/s/heuristic-brattain-0yjb9?file=/pages/index.js

**Comment by davidcetinkaya** [comment]
@siamahnaf198 the issue happens when I clone your sandbox. Try cloning the sandbox and maybe you should see the error.

**Comment by siamahnaf198** [comment]
Sorry!

At first thank you David for Spending time with me.

Secondly I am new in CodeSandBox. If you can do that without cloning it or see the issue in output by clicking open modal button. It will very helpful for me.

Actually I use embla carousel almost all my project when I start react and next js. But in my current project, I want to put embla carousel in a modal. Here I see that it not working. I try it for 7 days, But I fail.

Embal carousel is very light weight carousel. That's why I choose this carousel very much. If you can solve the problem it will be very helpful for me otherwise I have to tell my client to change project design.

**Comment by siamahnaf198** [comment]
Hello @davidcetinkaya 

I solve the error issue. Now you can clone it and Check Casrousel issue. Please help me to solve not running Embla carousel in modal.

New CodeSandBox link - https://codesandbox.io/s/reverent-pine-vl5mh

**Comment by davidcetinkaya** [comment]
Here you go @siamahnaf198, here's a [working CodeSandbox](https://codesandbox.io/s/tender-chaplygin-4ns89). The issue was that you're trying to initialise Embla before the modal is visible and has any width and height dimensions that's readable. Embla can't pick up a width and height of it's container when these dimensions doesn't exist.

So the solution is really simple, we just pass the `emblaRef` to the carousel when the modal is in a visible state, otherwise we pass `null`:

```jsx
<div ref={visible ? emblaRef : null} className="embla" sx={styles.embla}>
  ...content
</div>;
```

David

**Comment by siamahnaf198** [comment]
Wow:) It's working.

Thank you very much David. I never forgive you.
