### ISSUE TITLE
Buttons are not enabled/disabled when resizing the browser

### ISSUE THREAD

**Issue by eleikopetter** [davidcetinkaya/embla-carousel#216]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [x ] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.0

### Describe the bug

Buttons/arrows are not enabled/disabled when resizing the browser. 

### CodeSandbox

https://codesandbox.io/s/embla-carousel-disable-enable-buttons-on-resize-7i8mb

### Steps to reproduce

1. Resize browser < 768px to view slide size 50% and above is 25%.
2. Watch styling of enabled/disabled arrows and click to slide.

### Expected behavior

Arrows and dots to be updated and enabled/disabled when resizing the browser while using different slide sizes depending on browser size.

### Additional context

Many thanks for an awesome carousel! I am using it with React and Tailwind in my project and it's the only one I've found so far that I can use well with Tailwind CSS.

**Comment by davidcetinkaya** [comment]
Hi @eleikopetter,

Thank you for your bug report. What happens if you add the following code:

```js
useEffect(() => {
  if (!embla) return;
  onSelect();
  setScrollSnaps(embla.scrollSnapList());
  embla.on("select", onSelect);

  // Add this
  embla.on("resize", () => {
    embla.reInit();
    onSelect();
    setScrollSnaps(embla.scrollSnapList());
  });
}, [embla, onSelect]);
```

Cheers,
David

**Comment by eleikopetter** [comment]
Hi @davidcetinkaya ,

Works like a charm. Many thanks!

All the best,
Petter

**Comment by davidcetinkaya** [comment]
Glad to hear that @eleikopetter. Enjoy 🎉.
