### ISSUE TITLE
Cannot render grid of slides in one single view

### ISSUE THREAD

**Issue by eleikopetter** [davidcetinkaya/embla-carousel#218]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.0

### Describe the bug

I want to have a carousel that changes from carousel (with loop) < 992px to displaying grid > 992px. I don't know how to get this to work since the loop option offsets the first to slides from the left, never rendering the full grid in one view.

I am using Tailwind CSS so I cannot use any breakpoint settings through :before pseudo-element since the content is not allowed.

Greatful for any help!

### CodeSandbox

https://codesandbox.io/s/embla-carousel-default-react-forked-fgl0b

### Steps to reproduce

Resize the browser to go from 1 slide per view, to 2 slides per view (>768px), to an attempt of a full grid (>1024px)

### Expected behavior

- The intention is to display a full grid and pause the slider in 

### Additional context

- Add any other context about the problem here, like screenshots or similar.

**Comment by eleikopetter** [comment]
The solution is perhaps obvious: changing breakpoints options in JS instead. Please let me know if there is a better way to do this and/or if there is a better way to disable the carousel temporarily. Many thanks!

```
embla.on("resize", () => {
  if(window.innerWidth > 1024) {
      embla.reInit(setEmblaOptions({loop: false, draggable: false}));
  } else {
      embla.reInit(setEmblaOptions({loop: true, draggable: true})); 
  }
}
```

**Comment by davidcetinkaya** [comment]
Hi @eleikopetter,

I'm not 100% sure about what you want to achieve. Do you want to disable the carousel entirely when the screen size is `>= 992px`? **If the answer is no**, then you can set breakpoint specific options with plain CSS like so:

```css
@media (min-width: 992px) {
  .embla__viewport:before {
    display: none;
    content: '{ "loop": false }';
  }
}
```
You can read more about it [on this page](https://www.embla-carousel.com/guides/breakpoints/#changing-options) in the docs.

**If the answer is yes**, you can simply pass `null` instead of the `emblaRef` to the carousel viewport like so:

```jsx
<div className="embla" ref={isBreakpointMedium ? null : emblaRef}>
  ...
</div>
```
And Embla will remove the loop offset on the slides when destroying the active carousel.

Lycka till 😉.
David

**Comment by davidcetinkaya** [comment]
@eleikopetter did my [answer](https://github.com/davidcetinkaya/embla-carousel/issues/218#issuecomment-922036903) solve your problem?

**Comment by davidcetinkaya** [comment]
@eleikopetter closing this issue in 3 days if I don't get any response.

**Comment by eleikopetter** [comment]
@davidcetinkaya Thanks David, appreciate your answer! I had to solve it with JS per my previous comment since I am using Tailwind in the project and that does not allow for having a pseudo element with such content. That's one of the few limitations I've noticed so far when working with embla and tailwind. Keep up the good work! tack!
