### ISSUE TITLE
[Vanilia Javascript] How can i show dots and auto play slides?

### ISSUE THREAD

**Issue by buinguyenhoangtho** [davidcetinkaya/embla-carousel#223]
Hi author. First of all, this is my first time using **embla-carousel** . I'm just curious can i setup **autoplay** function and showing **dots** of multiple slides by using only vanilia javascript?. The **codesandbox** is for ReactJS iirc. How about javascript vanilia only? ( non reactJS or none npm?)

**Comment by davidcetinkaya** [comment]
Hi @buinguyenhoangtho,

You’ll have to combine the code from these two CodeSandboxes yourself:

- [Autoplay](https://www.embla-carousel.com/examples/inspiration/#autoplay)
- [Dots & Arrows](https://www.embla-carousel.com/examples/inspiration/#autoplay)
- 
Just click on the `VanillaJs` link next to the example carousel.

Best,
David

**Comment by buinguyenhoangtho** [comment]
Hi @davidcetinkaya . Thanks for your quick reponese. But my site is not using any npm/node package . . It completely static with HTML + Javascript Are there another way?

**Comment by davidcetinkaya** [comment]
Hi again @buinguyenhoangtho,

In that case you can use a CDN as described in the [docs](https://www.embla-carousel.com/get-started/cdn/).

Best,
David

**Comment by buinguyenhoangtho** [comment]
Yes i'm using CDN but it not support autoplay or dots. i guess

**Comment by davidcetinkaya** [comment]
Hi @buinguyenhoangtho,

The arrow/dots and autoplay functions are simply JavaScript functions and has nothing to do with NPM or CDN. You can simply copy and paste these functions into any environment that runs JavaScript, whether you have a NPM or CDN setup, or any other setup for that matter.

Judging from you response, you might be new to JavaScript, and that's totally fine. We've all been there at some point. But it's very important to keep the Embla Carousel issues, discussions and other Embla forums relevant to questions regarding Embla. I have very limited time and I can't create examples that cover every single use case out there. What you want to achieve is not an issue with Embla.

My recommendation is that you join the JavaScript group on Reddit and ask for help there. My experience is that people are quite helpful there and I'm sure that you'll get some help with what you want to achieve.

Best of luck!
David
