### ISSUE TITLE
Disable scroll when last slide is visible when multiple slides are visible in viewport and align is different than center

### ISSUE THREAD

**Issue by radeno** [davidcetinkaya/embla-carousel#228]
### Bug is related to

- [x] The Vanilla JavaScript version
- [x] The React version
- [x] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v5.0.1

### Describe the bug

- When **align** option is set to **start** or **end** and slide size is smaller than viewport (multiple slides on viewport, based on guide https://www.embla-carousel.com/guides/slide-sizes/) scrolling is still available even last slide is in the viewport.

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-default-react-forked-dn803?file=/src/js/EmblaCarousel.js

### Steps to reproduce

1. Go to 'provided sandbox url'
2. Click on 'next button' or drag it with mouse/touch
3. We are able to scroll even last slide is shown

### Expected behavior

- When align start or end is selected and slide size is smaller than block viewport, moving to the next slide should be disabled when the last slide is reached.

### Additional context

I like this module :)

**Comment by radeno** [comment]
My blindness. sorry. 

Anyway for anybody who will search for response. use:
```
containScroll: "trimSnaps"
```
to handle same situation as I have.

Maybe adding this information into guidelines as notice can prevent situations as I escalated :)

**Comment by davidcetinkaya** [comment]
@radeno thanks for leaving the [helpful tip](https://github.com/davidcetinkaya/embla-carousel/issues/228#issuecomment-931041344) you left here. 

> Maybe adding this information into guidelines as notice can prevent situations as I escalated :)

If you have any suggestions about how to do this more specifically, please share. I just want to mention that the search feature of the documentation website is very useful. If I type **space** in the search input, the `containScroll` **option** shows up as the first hit:

<img width="1155" alt="search" src="https://user-images.githubusercontent.com/11529148/135855015-bc9640b8-8ef0-4dee-a1a8-72ca066b9dbe.png">

..so a good place to always start is to use the search feature 🙂.

Cheers!
David
