### ISSUE TITLE
Thumbnail navigation example doesn't seem to work with vertical thumbnail navigation layout

### ISSUE THREAD

**Issue by bundit** [davidcetinkaya/embla-carousel#231]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [X] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.03

### Describe the bug

- Thumbnail navigation via two embla carousels does not work when thumbnail carousel is set to vertical. The thumbnail carousel seems to want to recognize as a horizontal one

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-thumbnails-react-forked-b34hv?file=/src/css/embla.css

### Steps to reproduce

1. Fork thumbnail example
2. Add flex direction column to thumbnail carousel container (.embla__container--thumb)
3. Add fixed height to thumbnail carousel container (.embla__container--thumb)
4. Clicking thumbnails does not navigate the thumbnail carousel and swiping the main carousel does not navigate the thumbnail carousel

### Expected behavior

- Clicking a thumbnail and swiping the main carousel should center the current thumbnail 

### Additional context

- N/A

**Comment by davidcetinkaya** [comment]
Hi @bundit,

Have you set the thumbnail carousel options to vertical with the [axis](https://www.embla-carousel.com/api/options/#align) **option**?

David

**Comment by bundit** [comment]
@davidcetinkaya Seems like I didn't read the docs well enough :) thanks for your help
