### ISSUE TITLE
Autoplay: progress bar with play and pause

### ISSUE THREAD

**Issue by andyjamesn** [davidcetinkaya/embla-carousel#232]
### Feature request is related to

- [x] The Vanilla JavaScript version
- [x] The React version
- [x] The Embla Carousel core (all versions)
- [x] Documentation website
- [ ] Other

### Is your feature request related to an issue?

Not related to an issue

### Describe the solution you'd like

A progress bar that displays between slide changes when set to autoplay. Not needed but related would be play and pause methods

The functionality can be seen on
https://splidejs.com/guides/autoplay/

### Describe alternatives you've considered

SpliderJS does this but I prefer embla due to its simplicity and freedom to control layout more from CSS than relying on JS options

**Comment by StevenVerbiest** [comment]
@davidjerleke I have the same problem as OP, but I think you misunderstood the question. 
The progress in the splidejs example is the progress of the `autoplay` delay, not the progress of the whole slider. 
I'm trying to find a way to get the get and display the remaining delay. I don't think the api currently exposes this information?

**Comment by davidjerleke** [comment]
@StevenVerbiest that's correct, it doesn't expose that information. However, it fires events that will let you know when it starts playing and stop playing like so:

```ts
emblaApi.on('autoplay:play', () => { /* Your callback */ })
emblaApi.on('autoplay:stop' () => { /* Your callback */ })
```

Best,
David
