### ISSUE TITLE
Fade Animation

### ISSUE THREAD

**Issue by andyjamesn** [davidcetinkaya/embla-carousel#233]
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [ ] The Embla Carousel core (all versions)
- [x] Documentation website
- [ ] Other

### Is your feature request related to an issue?

No

### Describe the solution you'd like

Add a fade effect on change. I was looking at the demo and I am sure if must be pretty similar to the scale example:

https://codesandbox.io/s/embla-carousel-scale-vanilla-gc3b0

I did look at it to see if I could adapt it but was not quite sure how to add this

It would be something like setting the CSS to change opacity with a transition eg:

transition: opacity 1250ms ease-in-out;

**Comment by davidcetinkaya** [comment]
Hi @andyjamesn,

This has been brought up a lot of times. I’m guessing you haven’t searched the issues for fade.

Here is [the answer](https://github.com/davidcetinkaya/embla-carousel/issues/39#issuecomment-568881867) to this.

David

**Comment by davidjerleke** [comment]
Released in [`8.1.0`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.0).
