### ISSUE TITLE
Bring the selected class back?

### ISSUE THREAD

**Issue by NachoVazquez** [davidcetinkaya/embla-carousel#239]
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Is your feature request related to an issue?

I tried to update to the latest version but now my project is working as expected because of the removal of the selected class.

Is there any heavy reason why this was removed? Is there any chance to bring it back?

Is there any alternative to accomplish the same result?

### Describe the solution you'd like

- A restoration of the selected class functionality or an alternative

**Comment by reco** [comment]
hey @NachoVazquez i think this is becoming a plug in https://github.com/davidcetinkaya/embla-carousel/issues/237

**Comment by NachoVazquez** [comment]
> hey @NachoVazquez i think this is becoming a plug in https://github.com/davidcetinkaya/embla-carousel/issues/237

Thanks @reco ! That makes sense then!

**Comment by davidcetinkaya** [comment]
Hi @NachoVazquez and @reco,

@reco, thanks for your [helpful response](https://github.com/davidcetinkaya/embla-carousel/issues/239#issuecomment-965731314)!

As @reco mentioned, I'm thinking about introducing the selected class logic in a plugin. Out of curiosity, do you think `draggableClass` and `draggingClass` is useful too? @reco feel free to leave your opinion here too.

Best,
David

**Comment by RectoVersoDev** [comment]
Hi,

For me the classNames `.is-draggable` & `.is-dragging` are useful for change the cursor (grab/grabbing)

Is there another way to achieve this simply ?

**Comment by NachoVazquez** [comment]
I agree those classes can become very handy, you could also increase the size of the element while grabbing to enhance the UX.

The draggable one is lest common to be used but I can see how someone could find use on that, like changing the cursor as @RectoVersoDev mentioned.

**Comment by davidcetinkaya** [comment]
Thanks for the input guys. I don’t use this myself so I’m not opinionated about what should be included in this plugin and not. Do you want all these classes to have defaults or should they be empty unless you pass a value to the plugin?

**Comment by RectoVersoDev** [comment]
Hello David,

1. Personally I don't have a preference, I let others say what they prefer

2. "ClassNames" seems good to me !

**Comment by davidcetinkaya** [comment]
For anyone interested:

The Class Name plugin has now [been released](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.2). Give NPM an hour or so to handle the first publish and it should be good to go.

- [Docs here](https://www.embla-carousel.com/plugins/class-names/)

**Comment by RectoVersoDev** [comment]
Thank you very much !

**Comment by NachoVazquez** [comment]
Awesome, thanks!

**Comment by PurviJha** [comment]
HI @davidcetinkaya i updated my carousel from 2.4.4 to its latest version in my carousel i have button on images consider if i have button on 4th image and while tabbing i got to 4th button so in that case my carousel scrolled to 4th slide but is-selected class is not adding to that slide . I also checked select event is also not initiating in tabbing case.i am adding lots of css based on is-selected class. in my older version i was not facing this issue select was also initiated while tabbing as well as is-selected class was also adding automatically. this is a accessibility issue for me. do we have a way to solve the issue.

**Comment by davidcetinkaya** [comment]
Hi @PurviJha,

You've actually the first person that noted this. That feature was [removed in v6](https://github.com/davidcetinkaya/embla-carousel/pull/229/files#diff-6c39bd3452524633d999714cd73bcdb99bc577a7689390204dd92ec993eca033). You should be able to create a plugin that with the code that Embla used when this feature was available like so:

```js
function SlideFocus(userOptions) {
  const options = Object.assign(
    {},
    defaultOptions,
    SlideFocus.globalOptions,
    userOptions,
  )
  let carousel
  let lastTabPressTime = 0

  function init(embla) {
    carousel = embla
    const { eventStore } = carousel.internalEngine()

    eventStore.add(document, 'keydown', registerTabPress, false)
    carousel.slideNodes().forEach(addSlideFocusEvent)
  }

  function destroy() {}

  function registerTabPress(event) {
    if (event.keyCode !== 9) return
    lastTabPressTime = new Date().getTime()
  }

  function addSlideFocusEvent(slide, index) {
    const { scrollTo, eventStore, options } = carousel.internalEngine()

    const focus = (): void => {
      const nowTime = new Date().getTime()
      const diffTime = nowTime - lastTabPressTime
      if (diffTime > 10) return

      carousel.rootNode().scrollLeft = 0
      const selectedIndex = Math.floor(index / options.slidesToScroll)
      scrollTo.index(selectedIndex, 0)
    }

    eventStore.add(slide, 'focus', focus, true)
  }

 const self = {
    name: 'SlideFocus',
    options,
    init,
    destroy,
  }
  return self
}

SlideFocus.globalOptions = undefined
```

...and use it like this:

### VanillaJs
```js
import EmblaCarousel from 'embla-carousel'
import SlideFocus from './SlideFocus'

const embla = EmblaCarousel(emblaNode, {loop:false}, [SlideFocus()])
```

### React
```js
import useEmblaCarousel from 'embla-carousel-react'
import SlideFocus from './SlideFocus'

function Carousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop:false }, [SlideFocus()])
}
```

Best,
David

**Comment by dathmart** [comment]
@davidcetinkaya Thanks so much for posting the SlideFocus plugin code. I had been trying to make the carousel fully keyboard accessible and was experiencing some strange behavior where the prevSlide button was being disabled and I couldn't swipe back to the beginning of the slide container after tabbing through the slides.

I had to slightly modify your code to fix a warning (e.g., refactoring registerTabPress to use event.code instead of event.keyCode) and make it work with TypeScript. Here is the modified plugin file:

```
// SlideFocus.ts
import { EmblaCarouselType, EmblaOptionsType } from 'embla-carousel-react';

// Plugin
const defaultOptions: EmblaOptionsType = {};
const globalOptions: EmblaOptionsType = {};
function SlideFocus(userOptions?: EmblaOptionsType) {
  const options = Object.assign(
    {},
    defaultOptions,
    globalOptions,
    userOptions
  );
  let carousel: EmblaCarouselType;
  let lastTabPressTime = 0;

  function init(embla: EmblaCarouselType) {
    carousel = embla;
    const { eventStore } = carousel.internalEngine();

    eventStore.add(document, "keydown", registerTabPress, false);
    carousel.slideNodes().forEach(addSlideFocusEvent);
  }

  function destroy() { }

  function registerTabPress(event: KeyboardEvent) {
    if (event.code !== 'Tab') return;
    lastTabPressTime = new Date().getTime();
  }

  function addSlideFocusEvent(slide: EventTarget, index: number) {
    const { scrollTo, eventStore, options } = carousel.internalEngine();

    const focus = (): void => {
      const nowTime = new Date().getTime();
      const diffTime = nowTime - lastTabPressTime;

      if (diffTime > 10) return;

      carousel.rootNode().scrollLeft = 0;
      const selectedIndex = Math.floor(index / options.slidesToScroll);
      scrollTo.index(selectedIndex, 0);
    };

    eventStore.add(slide, "focus", focus, true);
  }

  const self = {
    name: "SlideFocus",
    options,
    init,
    destroy,
  };
  return self;
}

export default SlideFocus;
```

Cheers,
Danny 🍻

**Comment by davidcetinkaya** [comment]
Hi @dathmart,

Thanks a bunch for the JS --> TS conversion 👍. If I have some time to spend some day, I'll improve the code and change the behaviour so the carousel only scrolls the bare minimum distance in order to show the newly tab focused element (similar to how browsers handles it). The solution above is a bit coarse and scrolls to the slide that contains the focused element. I'll release an official plugin if I get the opportunity.

Cheers and thanks!
David

**Comment by PurviJha** [comment]
thanks @davidcetinkaya  for posting the slide focus code.

**Comment by davidjerleke** [comment]
@PurviJha and @dathmart,

The `SlideFocus` feature has been added to the Embla core as of [v8.0.0-rc12](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc12). No need to add the SlideFocus code manually anymore.

Best,
David
