### ISSUE TITLE
Nested carousel content mapping, inner carousel working for only the first slide

### ISSUE THREAD

**Issue by shikhinee** [davidcetinkaya/embla-carousel#241]
I'm using this example https://codesandbox.io/s/embla-carousel-react-github-issue-141-eg8b1 to create a nested carousel.
When the slide counts are different for the nested carousel, I dynamically changed the slide counts. This seems to work fine, but it's not mapping all the images except for the first nest carousel slide. 2nd, 3rd, 4th, and all the other carousels seem to map only 1 image and the other slides are empty. On the above example can you dynamically change the nested carousel's slide? I don't seem to understand how it would import the media on the nested carousel as it has the same slide count and content for both the carousels.

**Comment by davidcetinkaya** [comment]
Hi @shikhinee,

If you’re dynamically changing slide counts, you need to tell this to the affected carousel/carousels. Using `embla.reInit()` might work.

Best,
David

**Comment by shikhinee** [comment]
Thanks for the reply @davidcetinkaya,
I've tried using the embla.reInit( ), but can't quite get to work it right. I've forked an example of my nested carousel using yours. Can you provide an example of the usage on this repro?
[https://codesandbox.io/s/embla-carousel-react-github-issue-141-forked-md3cn?file=/src/media/index.js&fbclid=IwAR3aP96YnnT9RRLPMrJFeAf7dwgkrYlPCjV-bxebHWD9VEuE2iN9n3Ss6_g](url)

**Comment by davidcetinkaya** [comment]
@shikhinee I don't understand the problem you're experiencing?

Best,
David

**Comment by shikhinee** [comment]
@davidcetinkaya second nested carousel should display 4 slides, but instead, it has 5 slides with 4 showing the content and 1 blank slide. Does embla.reInit() fix it?

**Comment by davidcetinkaya** [comment]
@shikhinee if you want me to look into this when I have time, you shouldn’t close the issue.

I’ve looked into this a little bit since the last time and it seems like you’re not passing the correct amount of slides to the nested carrousels. You’re passing the correct amount of photos but these don’t match the number of slides you’re passing.
