### ISSUE TITLE
how to get portion slides align to the edge

### ISSUE THREAD

**Issue by crazyxhz** [davidcetinkaya/embla-carousel#247]
First, very clean and light weight library, loves it!

But how can I achieve this: https://static.yximgs.com/udata/pkg/kuaishou-ad-frontend-cdn/Qo3cwcarousel.mp4

I want looped carousel with 80% width and 20px gap, but the first slide align to the edge.
Currently it is always centered by embla: 
https://codesandbox.io/s/embla-carousel-default-react-forked-hy62s?file=/src/css/embla.css

**Comment by davidcetinkaya** [comment]
Hi @crazyxhz,

I think you’re looking for the [`align`](https://www.embla-carousel.com/api/options/#align) option. Give it a try.

Best,
David

**Comment by crazyxhz** [comment]
> Hi @crazyxhz,
> 
> I think you’re looking for the [`align`](https://www.embla-carousel.com/api/options/#align) option. Give it a try.
> 
> Best, David

thanks, after I post this issue, I found the align option 😂
