### ISSUE TITLE
wheel-gestures not working?

### ISSUE THREAD

**Issue by siamahnaf198** [davidcetinkaya/embla-carousel#262]
Hello, I am trying to use Embla carousel with `drag free`,  `wheel-gestures`  and also with `progress`. But I am facing one problem When I am trying to integrate `embla-carousel-wheel-gestures`. It is not working. Here I am trying to scroll in `x-axis(horizontal)` with mouse wheel. Can you help me?

CodeSandBox- https://codesandbox.io/s/fast-fast-527jo

**Comment by davidcetinkaya** [comment]
Hi @siamahnaf198,

The Wheel Gestures package is not created and maintained by me. Please create this issue here instead:

- [https://github.com/xiel/embla-carousel-wheel-gestures/issues](https://github.com/xiel/embla-carousel-wheel-gestures/issues)

I’m closing this issue here.

Best,
David
