### ISSUE TITLE
Initial Carousel Blank

### ISSUE THREAD

**Issue by kush-daga** [davidcetinkaya/embla-carousel#263]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.0.2

### Describe the bug
Embla carousel is initially blank, and needs to be resized before it renders the image. This happens only sometimes and randomly. I have read the other issues regarding the same, but none of the tehniques work, I understand its a reinitializing issue but cannot figure out how to make it work. I am using it with NextJs 12.

I have the sample code to get started in this github repo - https://github.com/kush-daga/emblademo

### CodeSandbox

- The link to a CodeSandbox that demonstrates the bug clearly.

### Steps to reproduce

1.Clone the https://github.com/kush-daga/emblademo repo, and `yarn dev`.
2. Initially its a blank screen, resize to view images.

### Expected behavior

-  Carousel should work in the first render

### Additional context

https://user-images.githubusercontent.com/40840079/148800760-3ec6e86e-4314-4978-815c-f463d06a2aa1.mp4

**Comment by davidcetinkaya** [comment]
Hi @kush-daga,

You didn’t provide a CodeSandbox which makes it cumbersome for me to debug this and show you what needs to be changed in your code.

My initial guess is that you’re using the `init` event to run some functions. The issue with that event using the react package of Embla is that it probably fires before you get access to the API. So try replacing any code with the `init` event:

```js
embla.on("init", functionToRun)
```

…with:

```js
functionToRun()
```

I’m considering deprecating the `init` event because it only works as expected for vanillaJS users.

But as I said, I haven’t done any debugging so I’m not sure about this. If you want me to debug this further, please create a CodeSandbox and share the link.

Kindly
David

**Comment by kush-daga** [comment]
Thanks alot! And sorry for not providing a codesandbox, will try this out and if needed will create one. Also in this method now would I manually need to check if it's initialised?

**Comment by kush-daga** [comment]
Hey @davidcetinkaya I tried it out, doesnt seem to be working?

Here is the codesandbox link - https://codesandbox.io/s/strange-cherry-4s4rg?file=/components/CarouselComponent.tsx

Try refreshing or hard refreshing, it works sometimes, and sometimes its just blank as shown in the video

**Comment by davidcetinkaya** [comment]
@kush-daga thanks for the CodeSandbox link. I’ll do some debugging when possible.

**Comment by kush-daga** [comment]
@davidcetinkaya Alright thanks! Will wait.

**Comment by davidcetinkaya** [comment]
@kush-daga as I suspected this isn't a bug with Embla. There's a race condition that's causing your problem, because you're sometimes setting the height of the carousels before Embla has been initialized.

Here's a [working CodeSandbox](https://codesandbox.io/s/vibrant-bash-6d8ok?file=/components/CarouselComponent.tsx).

Best,
David

**Comment by kush-daga** [comment]
Hey thanks for this, but I think its still not working @davidcetinkaya, if u refresh the window and check, it sometimes would fail, leading to only a red background, and resizing it would render the images. 
![image](https://user-images.githubusercontent.com/40840079/148954924-7085747d-f0af-4294-a661-79424e3cd99a.png)
Like this

**Comment by davidcetinkaya** [comment]
@kush-daga I can’t reproduce the error in my CodeSandbox. How do you reproduce it?

**Comment by kush-daga** [comment]
> @kush-daga I can’t reproduce the error in my CodeSandbox. How do you reproduce it?

I just refreshed the window, probably try opening the screen in a new window, and try hard refreshing one or two times. Ill add a video to showcase the same if needed.

**Comment by davidcetinkaya** [comment]
@kush-daga, have you checked your console for errors?

**Comment by kush-daga** [comment]
Yep, nothing. @davidcetinkaya 

![image](https://user-images.githubusercontent.com/40840079/148956817-75b60b0f-0dc2-49fd-852e-2508648dda55.png)

Sometimes this also occurs, that a few images are rendered and few arent. I think the core issue is after I inspect the elements, is that the viewport has the height of `0px` applied to the style

**Comment by davidcetinkaya** [comment]
If that doesn’t work you’re probably doing some height reading things in the wrong order.

**Comment by kush-daga** [comment]
That doesnt work, so the reason for me having that height calculating function was to adjust for dynamic heights in diff slides. I feel that there is one way in which i dont encounter this, when I comment these

**Comment by kush-daga** [comment]
Im still figuring out if it actually fixes this and if it isnt causing any other side errors

**Comment by kush-daga** [comment]
Yeah this seems to fix it in my actual application code as well @davidcetinkaya it probably has something to do with calculating the heights initially.

**Comment by kush-daga** [comment]
https://codesandbox.io/s/bold-butterfly-u52p1?file=/pages/index.tsx

Here is a working link example, with multiple images as well of dynamic heights. Could be helpful to anyone else facing this issue

**Comment by davidcetinkaya** [comment]
@kush-daga thank you for sharing 👍🏻.

Just wanted to let you know that what you want to achieve will be available as an Embla plugin as soon as I get some time to make it:

- #237 

Best,
David

**Comment by kush-daga** [comment]
That would be wonderful, thanks!

**Comment by davidcetinkaya** [comment]
@kush-daga I've just released the **Auto Height plugin** with **v6.1.0**. Here's the [release details](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.1.0). Just make sure your slides have their natural height before initializing Embla so Embla can pick them up. So don't set `height: 0;` on your slides or similar.

Best,
David
