### ISSUE TITLE
Autoplay timer keeps running, even when viewport is inactive

### ISSUE THREAD

**Issue by openscript** [davidcetinkaya/embla-carousel#271]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [x] embla-carousel-autoplay
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- embla-carousel-autoplay: v6.0.2
- embla-carousel-react: v6.0.2

### Describe the bug

The bug seems to cause two problems.

#### Rushing through slides on reactivation of viewport

After having the carousel with autoplay in an inactive viewport (tab which is not displayed) and activating it again (coming back to the tab) after a while (10mins for example), you can see how the carousel rushes through several slides until it catches up with the timer.

https://user-images.githubusercontent.com/1105080/149907898-f7a3bdf0-038c-4362-9a4b-f6b36fc98dd2.mp4

#### Carousel disappears entirely

When leaving the carousel with autoplay for even longer in the background, the carousel will disappear. The reason for this is that the `transform` style on the carousel container has such a high negative value to move in in the x axis, that some browsers (Firefox especially) refuses to render the whole `<div>`.

![2022-01-16_17-11](https://user-images.githubusercontent.com/1105080/149908359-2cea5159-7cba-408b-938c-2424576e48ad.png)

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-autoplay-react-forked-openscript-ltd-slider-8h5bh

### Steps to reproduce

1. Open CodeSandbox mentioned above
1. Leave the tab for some time in the background
1. Come back to the tab and see the carousel rushing through the slides for a while

### Expected behavior

- The [timer](https://github.com/davidcetinkaya/embla-carousel/blob/864bf54514fc1d374266b663247b8c86a87a4ba4/packages/embla-carousel-autoplay/src/components/index.ts#L53) should be stopped, when the carousel is inactive.

### Additional context

Problem observed with
![image](https://user-images.githubusercontent.com/1105080/149908957-49080a14-70cf-4423-9d39-546cb91cea12.png)

**Comment by openscript** [comment]
Hi David (@davidcetinkaya),

you refactoring works perfectly for me and fixes the issue.

Thank you very much!

Robin

**Comment by davidcetinkaya** [comment]
Thanks @openscript!

I'll release a patch with the changes when possible.

Cheers,
David

**Comment by davidcetinkaya** [comment]
Hi @openscript,

This problem should be fixed in v6.1.1. Please try it out and let me know if it solves the problem.

Best,
David

**Comment by openscript** [comment]
Hi David @davidcetinkaya 

Thank you so much for the quick fix. It solves the problem :smiley: 

Robin
