### ISSUE TITLE
Unhandled Runtime Error when right clicking carousel image

### ISSUE THREAD

**Issue by AdamUhh** [davidcetinkaya/embla-carousel#272]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.1.0

### Describe the bug

- Note: I am using NextJS (But I also tested with React and the same thing happens)
When I right click the carousel (to inspect), it gives me an error: 
`Unhandled Runtime Error`
`TypeError: Cannot read properties of undefined (reading 'clientX')`

The code I used was taken from the Embla example page: [Arrows & Dots Example](https://www.embla-carousel.com/examples/navigation/)

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-arrows-dots-react-z5fbs?file=/src/js/EmblaCarousel.js

### Steps to reproduce

1. Go to the provided CodeSandbox [Link](https://codesandbox.io/s/embla-carousel-arrows-dots-react-z5fbs?file=/src/js/EmblaCarousel.js)
2. Right-click on the carousel (sometimes it will not appear instantly, so just right-click a few more times on the image)

### Expected behavior

- No error message.

### Additional context

- Here is a screenshot of the error message that pops up: ![Error](https://i.imgur.com/QjCW3CY.png)
- If this is even useful, here is a gif of me right-clicking the image a few times: ![Gif](https://i.imgur.com/1766sEa.gif)
- Problem observed with Chrome: ![Chrome Version](https://i.imgur.com/KqPx3ds.png)

**Comment by davidcetinkaya** [comment]
Hi @AdamUhh,

Thank you for creating this issue and providing useful information. I recently refactored the drag events so this must be a bug that I’ve introduced. I’ll investigate it when possible. 

Best,
David

**Comment by davidcetinkaya** [comment]
Hi @AdamUhh,

This problem should be fixed in [Release v6.1.1](https://github.com/davidcetinkaya/embla-carousel/releases). Please give it a go and let me know if it solves the problem.

Best,
David

**Comment by AdamUhh** [comment]
Hey,

Yea, the problem is fixed! Thanks for doing it so quickly 😄
