### ISSUE TITLE
Setting up multiple carousels on same page

### ISSUE THREAD

**Issue by MetaBureau** [davidcetinkaya/embla-carousel#28]
Possible / how to do something like this?

```javascript
import EmblaCarousel from 'embla-carousel';

var elements = document.querySelectorAll("li.carouselparent");

for (var i= 0; i < elements.length; i++) {
  const emblaNode = document.querySelector('.embla');
  const options = { loop: true };
  const embla = EmblaCarousel(emblaNode, options);
}
```

**Comment by davidcetinkaya** [comment]
Hi Stewart (@MetaBureau),

I've formatted your code to increase readability, I hope that's ok.

I'd like to understand what you want to achieve. Would you mind explaining a bit in words? For example, do you want to initialise/setup multiple carousels in the for loop? Or do you want to get all the slide nodes? Or am I missing something?

Kindly,
David

**Comment by MetaBureau** [comment]
Hi David, apologies and thanks.
I simply wish to display multiple carousels on the same page. Presently, without for statement, only the first .embla element is initialised.

**Comment by davidcetinkaya** [comment]
Hello again Stewart (@MetaBureau),

Thank you for clarifying. Here's one way to do it:

```javascript
var emblaNodes = [].slice.call(document.querySelectorAll(".embla"));
var options = { loop: true };

var emblaCarousels = emblaNodes.map(function(emblaNode) {
  return EmblaCarousel(emblaNode, options);
});

/*
The emblaCarousels variable now holds all carousels in an array
So if you want to do something with the first carousel you can do:

emblaCarousels[0].on("select", function() {
  console.log("The first carousel has changed selected slide!");
});
*/
```

If you want to see an example of how to setup dot, previous and next navigation please have a look at the code on this [CodeSandbox](https://codesandbox.io/s/oyols).

I hope this helps!

Best,
David

**Comment by MetaBureau** [comment]
Perfect thank you!

**Comment by davidcetinkaya** [comment]
@MetaBureau I'm glad I could help 🙂.

Cheers!
David

**Comment by MetaBureau** [comment]
Struggling a little with how to use navigation elements with multiple carousels.

**Comment by davidcetinkaya** [comment]
@MetaBureau would it help if I setup a CodeSandbox for you?

**Comment by MetaBureau** [comment]
Very much so. In my case, some carousels contain 1 slide, others 8.

**Comment by davidcetinkaya** [comment]
@MetaBureau I'll create one as soon as possible. Thanks for your patience 👍!

**Comment by davidcetinkaya** [comment]
Hello Stewart (@MetaBureau),

Here's a [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-28-gyst0) demonstration of how to initialise multiple carousels on a page with dot, previous and next navigation.

I hope this helps!

Best,
David

**Comment by MetaBureau** [comment]
You are a beautiful human being David! 
Thank you.

**Comment by davidcetinkaya** [comment]
Thanks Stewart (@MetaBureau), and I'm glad I could help 🙂.

If you like this project after trying it for some time and want to support it, please consider recommending it to a friend and/or giving it a star. Don't feel obligated to, but it really helps.

Cheers!
David

**Comment by sahilbrewari** [comment]
> 

This has helped a lot David. Thank you very much!

I do however have a question... How would I disable the carousel on a particular viewport?

Would really want to how to disable the lower carousel on full screen view considering if there are 3 products...

I am using it here... http://c8a08b5827.nxcli.net/

Thanks once again...

**Comment by davidjerleke** [comment]
Hi @sahilbrewari,

Thank you for [your question](https://github.com/davidjerleke/embla-carousel/issues/28#issuecomment-1122238685). But it's irrelevant to this issue. Please copy paste your question here instead: 

- #99 

If you're using React [this might be helpful](https://github.com/davidjerleke/embla-carousel/issues/99#issuecomment-688730519).

Kindly,
David
