### ISSUE TITLE
I can't get AutoHeight to play ball

### ISSUE THREAD

**Issue by JoshuaCrewe** [davidcetinkaya/embla-carousel#292]
### Bug is related to

- [ ] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [X] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.2.0

### Describe the bug

When using embla carousel with the autoheight plugin, the slide heights remain the same. The autoheight plugin detects each slide height as the same, which is to say the tallest slide in the pack.

### CodeSandbox

https://codepen.io/venncreative/pen/qBVerQL

(CodeSandbox doesn't play well with my Firefox browser)

### Steps to reproduce

1. Follow the "Get Started" section of the docs
2. Include AutoHeight plugin (either as module or CDN)
3. Include slides of different heights
4. When selecting new slides, the height remains the same

### Expected behavior

I would have expected the slide height for the embla container to change depending on which slide was currently active. In the demo above I included text underneath to show where the container ends.

### Additional context

I am sure I am misunderstanding how this plugin works and suspect that the flex styles are setting the height as all the same perhaps which is then detected by the JS. I am not sure though. I had no luck debugging the code, it is being loaded and it running, it just detects all the elements heights to be the same and presumably applying that.

I have implemented the wheel gestures plugin so I assume I am including plugins correctly.

**Comment by davidcetinkaya** [comment]
Hello @JoshuaCrewe,

Thank you for your question. This is happening because your images take time to load, and all images haven't loaded by the time you initialise your carousel (Embla). So Embla will pick up the slide heights at that very moment it's initialised. Please read [my answers](https://github.com/davidcetinkaya/embla-carousel/discussions/287#discussioncomment-2235042) in the following discussion from focused comment and downwards.

Let me know if it helps.

Best,
David

**Comment by JoshuaCrewe** [comment]
Wow. Thanks for getting back to me so quickly with that response!

I think I am following your logic here. The contrived example uses images as I thought that would be the simplest implementation to see and make. The actual implementation on the site I am working on it all text. I get the same behavior whatever I put in the slides.

I have created another pen which doesn't use images but plain text.

https://codepen.io/venncreative/pen/mdqNwWX

(I am also having a look at the classNames plugin and noticing that isn't doing anything for me either. Which is really enforcing the idea that I do not know what I am doing. It works in the codepen though so I can look at what my actual code is throwing.)

**Comment by davidcetinkaya** [comment]
Aha, I see what's happening there. I think your slides actually have the same height regardless of their content. And the reason for this is your CSS. If you set `display: flex` on your container, the default behaviour is that any element directly inside that container will have the same height as the highest child. So this should solve your problem:

```css
.embla__container {
  display: flex;
  align-items: flex-start; /* Add this */
}

Cheers,
David
```

**Comment by JoshuaCrewe** [comment]
Holy fudge! 

This absolutely solves the issue, THANKS! I wonder if we could include this in the docs? Would you consider a PR if I made one (I don't want to assume you would do any more work for me!)

**Comment by davidcetinkaya** [comment]
@JoshuaCrewe I would very much appreciate a PR 🙂!

**Comment by marcomezzavilla** [comment]
This is only loosely related to the original issue, but I'm leaving it here in case someone runs into a similar situation.

If you're using Embla and the autoplay plugin with a gallery that includes videos, make sure to initialize (or reinitialize) Embla **after** the video metadata has loaded — otherwise, you might get incorrect height calculations.

Something like this:
```js
document.querySelectorAll('video').forEach(video => {
  video.addEventListener('loadedmetadata', () => {
    embla.reInit()
  })
})
```
