### ISSUE TITLE
Console error: Uncaught TypeError: Cannot use 'in' operator to search for 'container' in null

### ISSUE THREAD

**Issue by fabianwurk** [davidcetinkaya/embla-carousel#295]
I have tried integrating as a module, but also the CDN method, but console is throwing the following error:

```
embla-carousel.umd.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'container' in null
    at b (embla-carousel.umd.js:1:11896)
    at T (embla-carousel.umd.js:1:12164)
    at A (embla-carousel.umd.js:1:14079)
    at (index):829:15
```

Any ideas why this may be happening?

**Comment by davidcetinkaya** [comment]
Hi @fabianwurk,

Thanks for your question. Please create a CodeSandbox with your code because I can’t guess what you’re doing.

Best,
David

**Comment by davidcetinkaya** [comment]
@fabianwurk did you see my [response](https://github.com/davidcetinkaya/embla-carousel/issues/295#issuecomment-1076649223)?

**Comment by fabianwurk** [comment]
Thanks @davidcetinkaya - that makes sense.
