### ISSUE TITLE
How to create a horizontal scroll slides with each slide contains several sub-slides that can be scrolled vertically?

### ISSUE THREAD

**Issue by xnslx** [davidcetinkaya/embla-carousel#296]
I came across Zara's website the other day, https://www.zara.com/us/, it is very interesting to see a horizontal carousel that for each container/slide that items in it can be scrolled vertically? I am trying to mimic the same carousel. But I am quite getting stuck.🤯 Here is the codesandbox, https://codesandbox.io/s/awesome-babbage-xf2gyh

**Comment by davidcetinkaya** [comment]
Hi @xnslx

[Here’s a CodeSandbox](https://github.com/davidcetinkaya/embla-carousel/issues/141#issuecomment-816659194) with nested carousels. I haven’t tried exactly what you want to achieve but it should be doable using a similar approach. Remember to set the [axis](https://www.embla-carousel.com/api/options/#axis) **option** to `y` on your nested carousels.

Kindly,
David

**Comment by xnslx** [comment]
@davidcetinkaya Wow. Thank you for such a quick reply on weekend! I will take a look! Thank you! Have a nice weekend!! 🌞

**Comment by xnslx** [comment]
@davidcetinkaya Hey David, it is working like a charm! Thank you for helping out.  I get exactly what i am looking for! Thank you! Have a wonderful week!

**Comment by davidcetinkaya** [comment]
@xnslx I’m happy you got it sorted. Cheers and enjoy!

Best,
David

**Comment by xnslx** [comment]
Hey David, I am trying to import the related code to my application. 

```
import React, { useState, useEffect, useCallback } from 'react';
import { PrevButton, NextButton } from "../EmblaCarouselButton";
import useEmblaCarousel from "embla-carousel-react";
import EmblaCarousel from 'embla-carousel';

import { useNestedEmblaCarousel } from '../useNestedEmblaCarousel'
import NestedCarousel from '../NestedCarousel';

const Carousels = (props) => {
    console.log('carousels', props)
    const { carousels, _key, _type } = props
   
    const [viewportRef, embla] = useEmblaCarousel();
    const setLockParentScroll = useNestedEmblaCarousel(embla);
    const [prevBtnEnabled, setPrevBtnEnabled] = useState(false);
    const [nextBtnEnabled, setNextBtnEnabled] = useState(false);
    const scrollPrev = useCallback(() => embla && embla.scrollPrev(), [embla]);
    const scrollNext = useCallback(() => embla && embla.scrollNext(), [embla]);
    const onSelect = useCallback(() => {
        if (!embla) return;
        setPrevBtnEnabled(embla.canScrollPrev());
        setNextBtnEnabled(embla.canScrollNext());
    }, [embla]);

    useEffect(() => {
        if (!embla) return;
        embla.on("select", onSelect);
        onSelect();
    }, [embla, onSelect]);


    return (
        <>
        <div className="embla">
            <div className="embla__viewport" ref={viewportRef}>
            <div className="embla__container">
                {carousels.map((s, index) => {
                console.log('s',s)
                return Object.values(s).map((j, index) => {
                    return (
                    <div className="embla__slide" key={index}>
                        <div>
                        {Object.keys(s).map((i, index) => {
                            return <span>{i}</span>;
                        })}
                        </div>
                        <div>
                        <NestedCarousel
                            slides={j}
                            setLockParentScroll={setLockParentScroll}
                        />
                        </div>
                    </div>
                    );
                });
                })}
            </div>
            </div>
            <PrevButton onClick={scrollPrev} enabled={prevBtnEnabled} />
            <NextButton onClick={scrollNext} enabled={nextBtnEnabled} />
        </div>
        </>
    );
}

export default Carousels
```

I always get error that 
<img width="965" alt="Screen Shot 2022-03-29 at 4 50 39 PM" src="https://user-images.githubusercontent.com/51500554/160713238-32944c46-330f-44ed-ad41-de761b1b8baa.png">

Do you have any idea how to fix it? it seems fine when it is in the codesandbox. 

Many thanks! Have a nice evening! 

Xian

**Comment by davidcetinkaya** [comment]
Hi @xnslx,

It's hard to know what's happening without your full setup and just seeing fragments of code. What do you have in your `package.json` file? I found one thing when skimming the code. Remove the following import:

 ```js
import EmblaCarousel from 'embla-carousel'; 
```

And remove `embla-carousel` from your `package.json`. `embla-carousel-react` already installs `embla-carousel` as a dependency.

```js
import React, { useState, useEffect, useCallback } from 'react';
import { PrevButton, NextButton } from "../EmblaCarouselButton";
import useEmblaCarousel from "embla-carousel-react";
import EmblaCarousel from 'embla-carousel'; // You shouldn't import this because you already have useEmblaCarousel
```

Best,
David

**Comment by xnslx** [comment]
@davidcetinkaya  Hey David, it is working like a charm! Many many thanks! Have a nice weekend!

Xian
