### ISSUE TITLE
Is there anyway to use this just with plain javascript?

### ISSUE THREAD

**Issue by callmehanu** [davidcetinkaya/embla-carousel#32]
Hi guys....
I'm just a **rookie dev**... in fact, I'm just code my portfolio with plane html, css and **javascript** and well, I thought this can be more easy to implement. 

I just wonder if there anyway to use this without **typescript** or anyway more simple?

**Comment by davidcetinkaya** [comment]
Hi Hanu (@callmehanu),

Thank you for your request. Of course it's possible, I will put together a demonstration and get back to you as soon as possible.

Thank you for your patience!
David

**Comment by davidcetinkaya** [comment]
Hello Hanu (@callmehanu),

I've created a 👉[CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-32-v14f7) to demonstrate how to use Embla Carousel only by including a `<script>` tag. TypeScript compiles to plain JavaScript so by adding the src to the [npm package script ](https://unpkg.com/embla-carousel@2.5.3/lib/index.js) you have access to `EmblaCarousel()` function globally like so:

```html
<script src="https://unpkg.com/embla-carousel@2.5.3/lib/index.js"></script>
<script>
  var emblaElement = document.querySelector(".embla");
  var options = { loop: false };
  var embla = EmblaCarousel(emblaElement, options);
</script>
```

I hope this helps!

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hi Hanu (@callmehanu),

Not to rush you but have you had the chance to check out the [CodeSandbox example](https://codesandbox.io/s/embla-carousel-github-issue-32-v14f7) yet?

Best,
David

**Comment by davidcetinkaya** [comment]
Hello Hanu (@callmehanu),

I'm closing this issue due to lack of response. Feel free to open this issue again if you don't think it's resolved.

Kindly,
David
