### ISSUE TITLE
Check if embla exists in ES6

### ISSUE THREAD

**Issue by jakubreron** [davidcetinkaya/embla-carousel#33]
Hello, i have a problem with checking if element exists and initializing the Embla carousel.

I want to do something like: If element exists on the page, then initialize it with Embla carousel, because when i do it without checking the element first, then on another subpage, i get an error saying "Error: No root element provided 😢"

My code looks like that:

```javascript
import EmblaCarousel from 'embla-carousel';

const testimonials = document.querySelector('.embla__testimonials');

const checkTestimonials = () => {
  return EmblaCarousel(testimonials, {
    align: 'center',
    containerSelector: '*',
    slidesToScroll: 1,
    containScroll: false,
    draggable: true,
    dragFree: false,
    loop: false,
    speed: 10,
    startIndex: 0,
    selectedClass: 'is-selected',
    draggableClass: 'is-draggable',
    draggingClass: 'is-dragging',
  });
}

if (testimonials.length) {
  checkTestimonials();
}
```

The code above doesn't work, it checks correctly for the element, but does not initialize the carousel, and i need to initialize it always after checking the element first :/

Does anyone know how i can solve it?
Thanks!

**Comment by davidcetinkaya** [comment]
Hi Jakub (@jakubreron),

Thank you for your question. Before I suggest a solution, I'd like to know if you are trying to initialise a single carousel or do you have multiple carousels on your page?

Kindly,
David

**Comment by jakubreron** [comment]
Hello, thanks for the quick answer, regarding the questions:

-  I will have that carousel on the homepage (but it will be used on more subpages), and i will have different carousel on another subpage.

My current HTML Code
```
<section class="section__presentation">
  <div class="[ embla  embla__testimonials ]  container">
    <ul class="embla__container">
      <li class="embla__slide  testimonial">
        <p class="testimonial__text">
          “The team ken are true rockstars when it comes to web design, development and delivering on time and on budget. They’ve made my previous experiences hiring agencies, seem like amateur hour. I recommend them without hesitation.”
        </p>
        <figure class="testimonial__person">
          <img src="{{ get_stylesheet_directory_uri() }}/assets/images/persons/john-khan.png" alt="John Khan">
          <figcaption>
            <strong class="testimonial__person-name">
              John Khan
            </strong>
            <span class="testimonial__person-position">
              VP Creative at Placester.com
            </span>
          </figcaption>
        </figure>
      </li>
    </ul>
  </div>
</section>
```

The problem is, i will have that carousel above on every subpage, expect only 1 page, so i need to initialize it in .js file, globally for every page, but when i go to that 1 subpage which doesn't has that HTML above, then i get the js error :/

**Comment by davidcetinkaya** [comment]
Hi Jakub (@jakubreron),

Thank you for the additional code and information. So I see one issue with the **JavaScript** code. The `document.querySelector()` returns two possible values.

1. If element is found, it returns an `element node`.
2. If not, it returns `null`.

It will never have the `.length` property because `document.querySelector()` will not look for a list of elements but rather a single element. So your **if statement** will always be falsy and never run the code inside it.

**A solution** for this is checking for `null` like so:

```javascript
import EmblaCarousel from 'embla-carousel';

const testimonials = document.querySelector('.embla__testimonials');

const checkTestimonials = () => {
  return EmblaCarousel(testimonials, {
    align: 'center',
    containerSelector: '*',
    slidesToScroll: 1,
    containScroll: false,
    draggable: true,
    dragFree: false,
    loop: false,
    speed: 10,
    startIndex: 0,
    selectedClass: 'is-selected',
    draggableClass: 'is-draggable',
    draggingClass: 'is-dragging',
  });
}

if (testimonials !== null) { // change this line
  checkTestimonials();
}
```

You can read more about `document.querySelector()` [on this page](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector).

I hope this helps, and would very much appreciate if you could confirm if this is working or not.

Best,
David

**Comment by jakubreron** [comment]
It works, you are amazing!!
Thank you so much!

**Comment by davidcetinkaya** [comment]
Thank you too, I’m glad I could help 🙂.
