### ISSUE TITLE
Version 3 - Draft & Discussion

### ISSUE THREAD

**Issue by davidcetinkaya** [davidcetinkaya/embla-carousel#36]
# Version 3 draft

This draft is subject to change and most likely will so stay tuned. Hit the **watch button** to do so:

<img width="1474" alt="watch" src="https://user-images.githubusercontent.com/11529148/70038056-ee557d80-15b7-11ea-8231-7289720ebd5a.png">

### Suggestions
Every suggestion such as feature requests or deprecation ideas will be added as a separate comment. Here's you chance to influence the future of Embla Carousel.

### Share your opinion - React with:
- 👍 If you like a suggestion.
- 👎 If you don't like a suggestion.
- 💬Comment if you want to discuss anything.

**Comment by davidcetinkaya** [comment]
## Github README documentation

Dropdowns with useful information and code examples should be added to the README. This goes for the following sections:

- Options,
- API methods
- Events

### Example
<img width="1045" alt="embla-readme" src="https://user-images.githubusercontent.com/11529148/70039018-78521600-15b9-11ea-9546-1b21f3d54a66.png">

**Comment by davidcetinkaya** [comment]
## 👉 Suggestion - Changing Drag/Pointer Events

As described in issue #22, the event names for drag interactions are unfortunate. 

### Renaming drag events
Considering the current implementation and behaviour of `dragStart` and `dragEnd` they should be renamed like below to better represent what they actually do:

- dragStart should be **renamed** to `pointerDown`.
- dragEnd should be **renamed** to `pointerUp`.

### Adding 2 new events
`dragStart` and `dragEnd` should actually behave as described below:

- `dragStart`: When pointer is down and has moved from its original position.
- `dragEnd`: When dragStart has fired and pointer is released.

**Comment by Kulevw** [comment]
Please, add value for slidesToScroll - auto.

**Comment by davidcetinkaya** [comment]
## 👉 Deprecation - Deprecate class name toggling

The frontend landscape is changing fast and with all the frameworks/libraries (like React, Vue, Angular, Svelte) out there it's not safe to assume that devs today use classnames to style their elements anymore. The following implementations should be removed from the Embla Carousel core and be up to the user to implement:

```javascript
// This suggestion is about deprecating the following features:
const emblaOptions = {
  selectedClass: 'is-selected',
  draggableClass: 'is-draggable',
  draggingClass: 'is-dragging'
};
```

**Comment by davidcetinkaya** [comment]
## 👉 Suggestion - Re-init API method

As described in issue #34, the only way to trigger a re-init of Embla is to call:

```javascript
embla.changeOptions({})
```
As described in the docs:

> Applies passed options by doing all the necessary calculations and initialising the carousel from scratch.

However, this doesn't read well if you only want to achieve a re-init and don't want to change any options. This suggestion is about exposing a method for this that reads better. I haven't decided the name yet but it will probably be something along this way:

```javascript
embla.reInit()

// or...

embla.lookForChanges()
```

**Comment by davidcetinkaya** [comment]
## Suggestion - Support for Y-axis

Add an option to enable a Y-axis carousel like so:

```javascript
const options = { axis: 'y' };
const embla = EmblaCarousel(emblaNode, options);
```
