### ISSUE TITLE
When opening the context menu while dragging mouseup is not being triggered

### ISSUE THREAD

**Issue by mrksmts** [davidcetinkaya/embla-carousel#37]
It is an edge case: 

When you right click while dragging and open the context menu and then release both mouse buttons the mouseup is not being triggered so you keep dragging till you click forcing a mousedown/up.

**Comment by davidcetinkaya** [comment]
Hello Mark (@mrksmts),

Nice catch! Thank you for reporting this 👍.
I will look into this and get back to you when I've done so.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi Mark (@mrksmts),

[Patch Release v2.6.4](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v2.6.4) should **solve this issue**. This issue also made me aware of that Embla listens for drag events even if the clicked mouse button isn't the left button. This is not intended and I've fixed that too. So thanks a lot 👍!

I'd very much appreciate if you could confirm if the patch works as intended.

Cheers!
David

**Comment by mrksmts** [comment]
Hi David (@davidcetinkaya),

Works like a charm!
Thanks a lot for fixing this so quickly!

Best,
Mark

**Comment by davidcetinkaya** [comment]
@mrksmts thanks for getting back to me 👍. I'm glad to hear that it works.

Have a nice one!
David
