### ISSUE TITLE
Create an option to block excessive scrolling

### ISSUE THREAD

**Issue by LaksCastro** [davidcetinkaya/embla-carousel#42]
Hi @davidcetinkaya ! 

Embla currently has ways to remove the leading and trailing blanks from the Slider (`containsScroll: true`), but still allow for excessive scrolling. It would be interesting to add an option to block this scroll and stop it when it reaches the end or beginning of the Slider. I would like to know what you think of this idea

Below is the example of the "excessive scroll" I am referring to

![Captura de Tela (21)](https://user-images.githubusercontent.com/51419598/71784931-c189f100-2fcf-11ea-9707-4d14a8474f5c.png)

**Comment by davidcetinkaya** [comment]
Hello Laks (@LaksCastro),
Thank you for this issue and I appreciate the screenshot 👍. 

When mentioning **excessive scroll**, are you referring to this [rubber band effect](https://gofile.io/?c=SywHFz) when the [loop](https://github.com/davidcetinkaya/embla-carousel#loop) option is `false` and the carousel is dragged against its edges?

Best,
David

**Comment by LaksCastro** [comment]
Yes, that's right. I would like to know what you think of including an option to block this rubber band effect. On many web sites, this effect is blocked. And particularly, within the UI I'm building, it would be great to have this option available. 

Thank you so much for reading the recommendation. 
I look forward to your reply :)

**Comment by davidcetinkaya** [comment]
Hello again Laks (@LaksCastro),

Thank you for clarifying! One more question: Do you want to block the excessive scrolling only when the user has finished dragging or entirely (even when pointer is down and dragging)?

Kindly,
David

**Comment by LaksCastro** [comment]
Exactly, totally block, as shown in [this short video](https://gofile.io/?c=LTOhB8) I recorded from a Slider mobile

Thank you, 
@davidcetinkaya

**Comment by davidcetinkaya** [comment]
Hello @LaksCastro!

I hope you’re all well 👍🏻. Sorry for the slow response here. So an update on this issue:

I’ve tested to achieve what you want locally but it kind of goes against Embla’s vision because Embla measures how rigorously a user drags the carousel in contrast to most other carousel libs. Most other libs only measure the drag direction and just assume the carousel should scroll one slide forward/backward. This is why they feel unnatural and very stiff. Overriding the drag force and blocking leading and trailing excessive scrolling would make the carousel feel unnatural.

However, Embla version 3 will soon be released where you can access the actual engine through the API. This will enable you to achieve what you want. As soon as I’ve released version 3 I will put together a CodeSandbox for you in order to demonstrate how to achieve what you want with just a few lines of code.

I hope this makes sense.

Best,
David

**Comment by LaksCastro** [comment]
Hi @davidcetinkaya!

Thank very much, 
Dont problem, feature request are hard to search and to integrate with the current features.

I understood what you meant by "unnatural and very stiff", and really, what makes me use Embla is its fluidity compared to other libraries. And I wait for the code in the CodeSandBox :)

I will close this Issue, but feel free to add the code of CodeSandBox on documentation, in README.md, why do I know people who would also like to have access to the snippet to be able to block the scroll.

Again, thank you, @davidcetinkaya

**Comment by joeyvanlierop** [comment]
Was an example ever added? I am unable to find anything on the [examples page](https://davidcetinkaya.github.io/embla-carousel/examples). and this feature would be quite useful to me 😁

**Comment by LaksCastro** [comment]
> Was an example ever added? I am unable to find anything on the [examples page](https://davidcetinkaya.github.io/embla-carousel/examples). and this feature would be quite useful to me 😁

@davidcetinkaya decided not to implement it for the reasons mentioned above in #issuecomment-625012863

**Comment by davidcetinkaya** [comment]
Hello Laks (@LaksCastro) and Joey (@joeyvanlierop)!

Thank you for your question Joey. The answer to your question is no, not yet. But I've quite recently added this to my list of things to investigate, together with issue #38. Please note that I can't promise any outcome but I will at least look into it further.

I can't give an ETA for this though. Public feature requests are progressing quite slow right now because of my lack of motivation. This is because of the very low visitor count and star count progression lately, as well as lack of this lib being promoted by others than me on social media (like Reddit for example).

I hope you understand.

Best,
David

**Comment by davidcetinkaya** [comment]
@jeiea, I've spent about 6 hours looking into this and I remember that I wasn't able to come up with a solution that I was satisfied with back then. As I mentioned in one of my earlier comments:

> I’ve tested to achieve what you want locally but it kind of goes against Embla’s vision because Embla measures how rigorously a user drags the carousel in contrast to most other carousel libs. Most other libs only measure the drag direction and just assume the carousel should scroll one slide forward/backward. This is why they feel unnatural and very stiff. Overriding the drag force and blocking leading and trailing excessive scrolling would make the carousel feel unnatural.

I wouldn't want to implement something that makes results in a very stiff feeling when dragging. Do you have any examples out there that solves this nicely without completely killing the fluid feel? That could help me try new approaches to this feature request.

Best,
David

**Comment by jeiea** [comment]
What I saw is [overscroll indicator](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html), but I'm afraid that it may not be what exactly you want. It can give a feedback of overscroll but not limited to fluid feel.

I don't know the reason why you are stick to fluid feeling, it's just a idea what I see. I guess that android apps maybe use glowing 
 effect more or less and iOS apps use bouncing overscroll.

**Comment by davidcetinkaya** [comment]
@jeiea I couldn't understand what the **overscroll indicator** is? It's just a yellow area in the example?

> I don't know the reason why you stick to fluid feeling, it's just a idea what I see.

I'm not quite sure what you mean by this. You don't think a fluid feeling is important? Or do you mean something else?

**Comment by jeiea** [comment]
My link wasn't accurate. What I imagined is similar to the following.

![android scrollview](https://user-images.githubusercontent.com/3159451/78423520-24d6fe00-7667-11ea-9dcb-f4687a22e0ed.gif)

I think fluid feeling is for feedback of scroll end. If there's no fluid physics or glow indicator, users may not be able to notice whether the app stops responding or scroll is finished in a short time. So I think both of them have same purpose and can be exchanged.

So I'm curious why you prefer one over the other. I read above comments again and got the keyword *stiff feeling*. Of course if user's drag is ignored completely at the scroll end it can give stiff feeling. But I don't think it is a problem and maybe android users familiar to that. And even I wanted this clamping physics behavior without glowing effect. I can't sure this is right in the respect of UX but I also don't know the reason to forbid this.

**Comment by jeiea** [comment]
You requested a new approach which preserve fluidity's advantage, but I don't think we should change the default behavior and the issue title is also includes 'option'.

So I think it is related to the degree of freedom. And it would be better if there's the reason why this should be limited.

**Comment by davidcetinkaya** [comment]
Thank you for the GIF @jeiea. It makes much more sense what you mean now. 

> So I'm curious why you prefer one over the other. I read above comments again and got the keyword stiff feeling. Of course if user's drag is ignored completely at the scroll end it can give stiff feeling. But I don't think it is a problem and maybe android users familiar to that.

One of the main reasons for building this library is because I wasn't satisfied with how other libraries handle drag events. They're in my opinion very stiff and only measure drag direction and not force. It almost feels like you're trying to move a refrigerator when dragging them. This is in my opinion bad UX and that's why I prefer a fluid carousel. The speed and duration of the scrolling should be proportional to how vigorous the drag gesture is.

I haven't considered the overscroll indicator up until now and I'm willing to try it out. Can't promise anything and give an ETA though.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi @joeyvanlierop, @jeiea,

To anyone wanting to block excessive scrolling: You can use the following code snippet:

Something along these lines should work:
```js
const embla = EmblaCarousel(emblaNode, { skipSnaps: false });

const preventEdgeScrolling = (embla) => {
  const { limit, target, location, scrollTo } = embla.dangerouslyGetEngine();

  return () => {
    if (limit.reachedMax(target.get())) {
      if (limit.reachedMax(location.get())) location.set(limit.max);
      target.set(limit.max);
      scrollTo.distance(0, false);
    }
    if (limit.reachedMin(target.get())) {
      if (limit.reachedMin(location.get())) location.set(limit.min);
      target.set(limit.min);
      scrollTo.distance(0, false);
    }
  };
};

embla.on("scroll", preventEdgeScrolling(embla));
```

Cheers,
David

**Comment by devdpontes** [comment]
@davidcetinkaya  

Great job btw. Any possibility of having this included as an option, instead of having to add the code snippet manually?

**Comment by davidcetinkaya** [comment]
@devdpontes have you read the [announcement](https://github.com/davidcetinkaya/embla-carousel/issues/187#issue-873669552)?

Cheers,
David

**Comment by tgaeta** [comment]
Was this added to the docs?

**Comment by yunyu** [comment]
@davidjerleke The announcement 404s and there doesn't seem to be any mention of disabling overscroll in the docs. Just curious about if this is available!

**Comment by davidjerleke** [comment]
Hi @yunyu,

Thanks for your question. You can use the [following code snippet](https://github.com/davidjerleke/embla-carousel/issues/42#issuecomment-895850425). **Please note** that `dangerouslyGetEngine` in that snippet has been renamed to `internalEngine` from [v6](https://github.com/davidjerleke/embla-carousel/releases/tag/v6.0.0) and up.

Best,
David

**Comment by alexeymolchan** [comment]
> Hi @joeyvanlierop, @jeiea,
> 
> To anyone wanting to block excessive scrolling: You can use the following code snippet:
> 
> ```js
> const embla = EmblaCarousel(emblaNode, { skipSnaps: false });
> 
> const preventEdgeScrolling = (embla) => {
>   const { limit, target, location, scrollTo } = embla.dangerouslyGetEngine();
> 
>   return () => {
>     if (limit.reachedMax(target.get())) {
>       if (limit.reachedMax(location.get())) location.set(limit.max);
>       target.set(limit.max);
>       scrollTo.distance(0, false);
>     }
>     if (limit.reachedMin(target.get())) {
>       if (limit.reachedMin(location.get())) location.set(limit.min);
>       target.set(limit.min);
>       scrollTo.distance(0, false);
>     }
>   };
> };
> 
> embla.on("scroll", preventEdgeScrolling(embla));
> ```
> 
> Cheers, David

Hi, with latest rc 8.0.0-rc03 this code snippet doesn't work as good as in v7 - slide is rapidly jumping near the edge while finger is moved.

**Comment by davidjerleke** [comment]
Hi @alexeymolchan,

Thanks. Noted. I want to mention that this is not an official feature so it’s not prioritized. I have a lot on my to do list so I don’t know when I will be able to look into this.

Best,
David

**Comment by EarthlingDavey** [comment]
@davidjerleke great to see the v8 work. I've upgraded really easilly. Cool that we don't need clickAllowed any more :)

If you have time, could I have some pointers on how I can improve the above script for v8?

I'd be up for a hard limit or tightening the elasticity. 

I've naively added a class for css slow transforms when the limit is hit in an attempt to debounce the jitter effect. 

But, I'd like to do something a bit better, any suggestion would be welcomed.

Cheers

**Comment by davidjerleke** [comment]
@EarthlingDavey, @ameytessact does this work for you?

```ts
emblaApi.on('scroll', (emblaApi) => {
  const {
    limit,
    target,
    location,
    offsetLocation,
    scrollTo,
    translate,
    scrollBody
  } = emblaApi.internalEngine()

  let edge: number | null = null

  if (limit.reachedMax(location.get())) edge = limit.max
  if (limit.reachedMin(location.get())) edge = limit.min

  if (edge !== null) {
    offsetLocation.set(edge)
    location.set(edge)
    target.set(edge)
    translate.to(edge)
    translate.toggleActive(false)
    scrollBody.useDuration(0).useFriction(0)
    scrollTo.distance(0, false)
  } else {
    translate.toggleActive(true)
  }
})
```

**Comment by EarthlingDavey** [comment]
@ameytessact I'm sorry, I deleted it because it never really worked. 

In essence it was an on scroll listener that added a class to the embla component if the limit had been hit. It had a setTimeout to remove the class after 100ms. The css for class was something like `transition: transform 50ms`.

@davidjerleke Thank you! On MacOS it looks good in chrome, but it stutters when the limits are hit in Firefox & Safari.

**Comment by davidjerleke** [comment]
@EarthlingDavey thanks for testing. I'll have a look at it again when possible.

**Comment by davidjerleke** [comment]
> @davidjerleke Thank you! On MacOS it looks good in chrome, but it stutters when the limits are hit in Firefox & Safari.

@EarthlingDavey are you sure? I just tested this on both Firefox and Safari and it doesn't stutter at all when limits are hit. Did you try this on desktop or mobile? What version of Embla are you using?

Thanks in advance!
David

**Comment by EarthlingDavey** [comment]
1. I retested on my local react project and it was still jittering.
2. Forked one of your examples to make a minimal reproduction [Emble Thumbs - with scroll limits](https://codesandbox.io/s/embla-carousel-thumbs-react-no-excess-scroll-3thlsl?file=/src/js/EmblaCarousel.tsx)
3. That worked flawless in FF.
4. Wondered how my repo was different
5. Locally I commented out WheelGesturesPlugin() and AutoHeight()
6. Removed dep of `"embla-carousel": "8.0.0-rc11"` - I kept `"embla-carousel-react": "8.0.0-rc11",`
7. My issues on local were fixed!
8. Re-added `"embla-carousel": "8.0.0-rc11"` to confirm it was the cause of the jitter issue.
9. The issue did not come back as I expected.
10. I don't know why it's working now and not before. My package.json and yarn.lockhave not changed. I suspect something in node_modules has changed but I'm not sure.
11. Build via my pipeline and delpoy live ... scrollers are jitter free!

Cheers @davidjerleke - legend!

**Comment by davidjerleke** [comment]
@EarthlingDavey that's weird 🙂. Glad to hear that it works now. Let me know if you run in to trouble on any device or similar and I'll have another look and think of something.

Best,
David

**Comment by AkinAguda** [comment]
Got any fixes @davidjerleke? I experience this jitter too

**Comment by AkinAguda** [comment]
> @alexeymolchan, @EarthlingDavey, @ameytessact, @sudorock does this work for v8?
> 
> **TypeScript**
> 
> ```ts
> emblaApi.on('scroll', (emblaApi) => {
>   const {
>     limit,
>     target,
>     location,
>     offsetLocation,
>     scrollTo,
>     translate,
>     scrollBody
>   } = emblaApi.internalEngine()
> 
>   let edge: number | null = null
> 
>   if (limit.reachedMax(location.get())) edge = limit.max
>   if (limit.reachedMin(location.get())) edge = limit.min
> 
>   if (edge !== null) {
>     offsetLocation.set(edge)
>     location.set(edge)
>     target.set(edge)
>     translate.to(edge)
>     translate.toggleActive(false)
>     scrollBody.useDuration(0).useFriction(0)
>     scrollTo.distance(0, false)
>   } else {
>     translate.toggleActive(true)
>   }
> })
> ```
> 
> **VanillaJs**
> 
> ```ts
> emblaApi.on('scroll', (emblaApi) => {
>   const {
>     limit,
>     target,
>     location,
>     offsetLocation,
>     scrollTo,
>     translate,
>     scrollBody
>   } = emblaApi.internalEngine()
> 
>   let edge
> 
>   if (limit.reachedMax(location.get())) edge = limit.max
>   if (limit.reachedMin(location.get())) edge = limit.min
> 
>   if (edge !== null) {
>     offsetLocation.set(edge)
>     location.set(edge)
>     target.set(edge)
>     translate.to(edge)
>     translate.toggleActive(false)
>     scrollBody.useDuration(0).useFriction(0)
>     scrollTo.distance(0, false)
>   } else {
>     translate.toggleActive(true)
>   }
> })
> ```

I had the jitter issue and fixed it by tweaking @davidjerleke's solution a bit:

```
emblaApi.on('scroll', (emblaApi) => {
  const {
    limit,
    target,
    location,
    offsetLocation,
    scrollTo,
    translate,
    scrollBody
  } = emblaApi.internalEngine()

  let edge: number | null = null

  if (location.get() > -1) {
    edge = limit.max;
  }

  if (location.get() < limit.min + 1) {
    edge = limit.min;
  }

  if (edge !== null) {
    offsetLocation.set(edge)
    location.set(edge)
    target.set(edge)
    translate.to(edge)
    translate.toggleActive(false)
    scrollBody.useDuration(0).useFriction(0)
    scrollTo.distance(0, false)
  } else {
    translate.toggleActive(true)
  }
})
```

**Comment by fakundo** [comment]
I had the jitter too and fixed it with the modified code provided by @davidjerleke

```
emblaApi.on('scroll', (emblaApi) => {
  const {
    limit,
    target,
    location,
    offsetLocation,
    scrollTo,
    translate,
    scrollBody
  } = emblaApi.internalEngine()

  let edge: number | null = null

  if (location.get() >= limit.max) edge = limit.max;
  if (location.get() <= limit.min) edge = limit.min;

  if (edge !== null) {
    offsetLocation.set(edge)
    location.set(edge)
    target.set(edge)
    translate.to(edge)
    translate.toggleActive(false)
    scrollBody.useDuration(0).useFriction(0)
    scrollTo.distance(0, false)
  } else {
    translate.toggleActive(true)
  }
})
```

**Comment by colinnielsen** [comment]
If you need an option for disabling overscroll or rubberbanding on any slide, I modified the code from @fakundo to do so

```
api.on('scroll', emblaApi => {
        const {
          target,
          index,
          indexPrevious,
          location,
          scrollTo,
          translate,
          scrollBody,
        } = emblaApi.internalEngine();
        const direction = index.get() > indexPrevious.get() ? 'right' : 'left';
        let edge: number | null = null;

        if (direction === 'left' && location.get() >= target.get())
          edge = target.get();
        if (direction === 'right' && location.get() <= target.get())
          edge = target.get();

        if (edge !== null) {
          location.set(edge);
          target.set(edge);
          translate.to(edge);
          translate.toggleActive(false);
          scrollBody.useDuration(0).useFriction(0);
          scrollTo.distance(0, false);
        } else {
          console.log('active');
          translate.toggleActive(true);
        }
      })
      ```

**Comment by a-c-sreedhar-reddy** [comment]
Is there a way to get the rubberband effect at the end,
but the carousel should not scroll beyond certain distance.

**Comment by a-c-sreedhar-reddy** [comment]
Found the solution via chatGPT 🥇 
```
  emblaApi?.on("scroll", (emblaApi) => {
        const {
          limit,
          target,
          location,
          offsetLocation,
          scrollTo,
          translate,
          scrollBody,
          containerRect,
        } = emblaApi.internalEngine();

        let edge: number | null = null;
        const rubberBandWidth = containerRect.width * 0.25;
        if (location.get() >= limit.max + rubberBandWidth)
          edge = limit.max + rubberBandWidth;
        if (location.get() <= limit.min - rubberBandWidth)
          edge = limit.min - rubberBandWidth;

        if (edge !== null) {
          offsetLocation.set(edge);
          location.set(edge);
          target.set(edge);
          translate.to(edge);
          translate.toggleActive(false);
          scrollBody.useDuration(0).useFriction(0);
          scrollTo.distance(0, false);
        } else {
          translate.toggleActive(true);
        }
      });
```

**Comment by quankhuc** [comment]
> I had the jitter too and fixed it with the modified code provided by @davidjerleke
> 
> ```ts
> emblaApi.on('scroll', (emblaApi) => {
>   const {
>     limit,
>     target,
>     location,
>     offsetLocation,
>     scrollTo,
>     translate,
>     scrollBody
>   } = emblaApi.internalEngine()
> 
>   let edge: number | null = null
> 
>   if (location.get() >= limit.max) edge = limit.max;
>   if (location.get() <= limit.min) edge = limit.min;
> 
>   if (edge !== null) {
>     offsetLocation.set(edge)
>     location.set(edge)
>     target.set(edge)
>     translate.to(edge)
>     translate.toggleActive(false)
>     scrollBody.useDuration(0).useFriction(0)
>     scrollTo.distance(0, false)
>   } else {
>     translate.toggleActive(true)
>   }
> })
> ```

I found this solution has a problem when loop is set to true. I added a check for `loop` here, which is from opts that I passed in to my Vue composable. By modifying this check, it seems to enable loop to work well
```js
api.on('scroll', (emblaApi) => {
      const { limit, target, location, offsetLocation, scrollTo, translate, scrollBody } = emblaApi.internalEngine()

      let edge

      if (limit.reachedMax(target.get())) edge = limit.max
      if (limit.reachedMin(target.get())) edge = limit.min

      if (!opts.loop && edge !== undefined) {
        offsetLocation.set(edge)
        location.set(edge)
        target.set(edge)
        translate.to(edge)
        translate.toggleActive(false)
        scrollBody.useDuration(0).useFriction(0)
        scrollTo.distance(0, false)
      } else {
        translate.toggleActive(true)
      }
    })
```
