### ISSUE TITLE
Unnecessary scroll under certain conditions

### ISSUE THREAD

**Issue by olushchik** [davidcetinkaya/embla-carousel#46]
Hi! I ran into a nasty bug with unnecessary scroll under certain conditions:
- `loop`: `true`
- `draggable`: `false`
- `slidesToScroll`: more than 1 (for example 4)
- slides count: more than `slidesToScroll` but not completely divisible by `slidesToScroll` (for example 5)

In this case after initial load when we scroll to next and try to click link on the first slide we see unnecessary scroll.

Here's a demonstration of what I'm talking about: https://codesandbox.io/s/embla-carousel-containscroll-mec6x

As I figured out it is because click on the link fires `focus` event and Embla considers that this is not the current slide and does scroll.

**Comment by davidcetinkaya** [comment]
Hi Oleg (@olushchik),

Nice catch, and thank you for reporting this! I appreciate the clear CodeSandbox demonstration ⭐️.

As you mention, Embla acts on the focus event and wants to scroll the focused element into view. The behaviour is desired when a user navigates with the tab key. But it's not desired when clicking.

Right now I'm working with issue #23 (`scrollBy`) and it might take some time for me to investigate this further in order to release a patch. Feel free to submit a **pull request** if you want.

Best,
David

**Comment by olushchik** [comment]
Hi, David! Thanks for the response!

>  This behaviour is desired when a user navigates with the tab key for accessibility reasons.

Oh, now I understand for what reasons this was done 😃  But I'm not sure that I understand how to fix it properly 😢

**Comment by davidcetinkaya** [comment]
Hello Oleg (@olushchik),

No worries 🙂. This issue will have to wait then. I appreciate you taking time to report this!

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hello Oleg (@olushchik),

The [following commit](https://github.com/davidcetinkaya/embla-carousel/commit/c91ba1c6e72988b990d9c375a64309a846f4cc63) includes a fix for this bug. Embla Carousel Version 3 is just around the corner so the bug fix will be released with version 3.

Thanks for taking time to create this issue 👍!

Best,
David

### This bug has been fixed and will be released with version 3.

**Comment by olushchik** [comment]
Thanks a lot, you are the best!

**Comment by davidcetinkaya** [comment]
Hello @olushchik,
 
This bug has been fixed and is ready for test if you grab the latest version. Note that it's a major version release so please read the [instructions here](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.0).

I would very much appreciate if you could confirm if this is working as expected now and the bug has been solved.

**Comment by davidcetinkaya** [comment]
Have you had the chance to test this @olushchik? Thanks in advance.

**Comment by olushchik** [comment]
Unfortunately, no. Just tested in sandbox, works fine.

**Comment by davidcetinkaya** [comment]
@olushchik so this issue is resolved then 🙂?

**Comment by olushchik** [comment]
I reread my message and realized that it was not clear)) I meant that I did not check this in my real project, but only in the sandbox. And looks like the issue is resolved 👍

**Comment by davidcetinkaya** [comment]
Awesome, thank you for your feedback. I'm closing this issue and thanks for reporting this 👍.
