### ISSUE TITLE
Fit the first item to the left when I have slides with fixed sizes?

### ISSUE THREAD

**Issue by yocmen** [davidcetinkaya/embla-carousel#54]
Hi, how can I fit the first item to the left when I have slides with fixed sizes?

I'm using the {align: "start"}, but I can't make it work, I'm trying to make it responsive putting the slides from the Left, maybe grouping cells? Thanks in advance.

here is the codepen [https://codesandbox.io/s/embla-carousel-dragfree-k1ro4](https://codesandbox.io/s/embla-carousel-dragfree-k1ro4)

**Comment by davidcetinkaya** [comment]
Hello Yocsel (@yocmen),
Thank you for your question.

I think you've missed to add `align: start` to the Embla Carousel options:

<img width="994" alt="embla" src="https://user-images.githubusercontent.com/11529148/78586633-ffe7b400-783b-11ea-9cb3-da2f37ef7d3d.png">

If you take look at the provided screenshot on line 17, you need to change it to:

```javascript
const embla = EmblaCarousel(viewPort, { dragFree: true, align: 'start' });
```

Let me know if this helps!

Best,
David

**Comment by yocmen** [comment]
hooooo, I miss-spelled the property :(, please forgive me 🤦‍♂️

**Comment by davidcetinkaya** [comment]
@yocmen no worries 🙂. Thank you and enjoy!
