### ISSUE TITLE
Bug while destroying carousel

### ISSUE THREAD

**Issue by ogheo** [davidcetinkaya/embla-carousel#63]
<img width="632" alt="Screen Shot 2020-05-22 at 22 43 16" src="https://user-images.githubusercontent.com/6599359/82704259-d238bc00-9c7d-11ea-94b9-7bc9bfeca0d8.png">

**Comment by davidcetinkaya** [comment]
Hello Oleg (@ogheo),

Please provide a code example of how you’ve setup the carousel. I need that I order to see why this is happening and confirm if it’s an actual bug with the package or not.

Kindly
David

**Comment by davidcetinkaya** [comment]
Duplicate of [Embla Carousel React](https://github.com/davidcetinkaya/embla-carousel-react/) issue [#13](https://github.com/davidcetinkaya/embla-carousel-react/issues/13).
