### ISSUE TITLE
width problem if show/hide or remove some items

### ISSUE THREAD

**Issue by khanitnanj** [davidcetinkaya/embla-carousel#68]
sorry, I don't know how to explain.

the problem is

if I have 20 items in slide. I filter it to 5 items, width of slide is not fit (still same 20items)

How to fix it.

I have Code sandbox 
https://codesandbox.io/s/embla-carousel-react-basic-setup-0ky1p?file=/src/js/index.js

**Comment by davidcetinkaya** [comment]
Hello @khanitnanj,

Thank you for your question. This is because you have to tell Embla that something changed. So do it like this when you filter the number of items:

**Version 3 and up:**

```javascript
embla.reInit({}) // Updates Embla
```

**Versions below 3:**

```javascript
embla.changeOptions({}) // Updates Embla
```

**Comment by khanitnanj** [comment]
It's work, but I have to reInit it twice times

First, embla.reInit({}) 
Then embla.reInit(myOptions)

Thank you for Super Fast Reply!

Love your library.

**Comment by davidcetinkaya** [comment]
@khanitnanj no worries. Would you mind sharing your code so I can take a look?

**Comment by khanitnanj** [comment]
Oh, I changed my element structor, and now working with reInit one time.

it's my fault. 

Thank your for your support.

**Comment by davidcetinkaya** [comment]
Glad to hear that. Enjoy 🙂.
David
