### ISSUE TITLE
Feature: items option

### ISSUE THREAD

**Issue by gianlucacandiotti** [davidcetinkaya/embla-carousel#69]
Hello! First of all, I discovered the library recently and seems very nice and active, props on the hard work.

So I'm building a web page and will show some carousels in different sections. Initially I was planning on building my own since most other options have many dependencies, but quickly started over engineering so I was very pleased to find this. One thing I would really like to have is carousels with different number of items per slide, but individual snap points. Owl Carousel supports this option, you can see how it works [here](https://owlcarousel2.github.io/OwlCarousel2/demos/responsive.html).

I could also give it a shot at contributing in case this seems like something you would see as a fit to the project, or if there is a way to achieve this from the consumers please tell me. Anyways if you can point me in the right direction I would appreciate it.

This would also enable another feature I would like to implement which is handling different numbers of items according to media queries. Owl Carousel has that baked into the API, but by supporting the `items` options, consumers could implement this functionality.

Thanks!

**Comment by davidcetinkaya** [comment]
Hello Gianluca (@gianlucacandiotti),

Thank you for tour feature request. By the sound of it, Embla Carousel supports this out of the box. You can set any desired width for your slides and Embla will pick that up. Try this:

1. Open this [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-69-bppew).
2. Open the following file `src/css/embla.css`.
3. Find the class name `.embla__slide`.
4. Set the width to anything you like.

About the **breakpoints**, you can just change the slide widths in CSS and Embla will pick it up. Like so:

```css
.embla__slide {
  width: 100%;
}

@media (min-width: 768px) {
  .embla__slide {
    width: 25%;
  }
}
``` 

Let me know if this helps!
David

**Comment by gianlucacandiotti** [comment]
Hey David!

Thanks a lot for taking the time to look into this. Yeah, you're right, it works the way I need it 😄  Maybe it would be worth to add this to the examples.

Keep up the great work!
Gianluca

**Comment by davidcetinkaya** [comment]
Thank you for asking. I'm happy that it was what you were looking for 🙂. And I agree, I should build a better showcase page. It's kind of hard to get the time needed to do so but I'll do my best to improve it. Thanks for your suggestion 👍.

Have a great day and let me know if you have further questions.

Best,
David
