### ISSUE TITLE
New Feature: Add cssClass to the selected slide

### ISSUE THREAD

**Issue by SLMNBJ** [davidcetinkaya/embla-carousel#7]
Would be helpful to animate some elements inside the slide when is selected.

**Comment by davidcetinkaya** [comment]
Hi @SLMNBJ ,
With version [0.3.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v0.3.0) it's possible to **choose css class** of your liking for the selected slide. If you don't specify a css class Embla will use the default class which is **is-selected**.

Read about how to achieve this [here](https://github.com/davidcetinkaya/embla-carousel#options).

I'm closing this issue. Thanks for reporting this.

Enjoy!
