### ISSUE TITLE
Installation without any manager

### ISSUE THREAD

**Issue by DominiqueVial** [davidcetinkaya/embla-carousel#70]
Could you please provide a way to use it without npm?
Thank you?

**Comment by davidcetinkaya** [comment]
Hello @DominiqueVial,

Thanks for your question.
Please take a look at 👉🏻 [this issue](https://github.com/davidcetinkaya/embla-carousel/issues/32#issuecomment-547003593).

Let me know if it helps!
David

**Comment by davidcetinkaya** [comment]
Duplicate of #32.

**Comment by DominiqueVial** [comment]
Thank you!

**Comment by davidcetinkaya** [comment]
No worries @DominiqueVial, enjoy 🙂.

**Comment by davidcetinkaya** [comment]
FWIW [here's a demonstration](https://davidcetinkaya.github.io/embla-carousel/#cdn-usage) of how to install Embla without a package manager.
