### ISSUE TITLE
Type definition file refers to files that don't exist in the build

### ISSUE THREAD

**Issue by korsvanloon** [davidcetinkaya/embla-carousel#75]
The index.d.ts file that is generated refers to files in the vanilla folder.
This folder does not exist anymore in the npm package.
Therefore the typings break.

**Comment by davidcetinkaya** [comment]
Hello @korsvanloon,

Thank you for reporting this. You’re right, it’s because the folder is not included in the `files` array in `package.json`, but it should be there.

I’ll release a patch fix as soon as possible and will let you know when it’s ready to consume.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hi again @korsvanloon,
Release [v.3.0.17](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.17) should include the missing type definition files. Enjoy!

Best,
David

**Comment by korsvanloon** [comment]
Very quickly! Thank you so much!
