### ISSUE TITLE
Invalid hook call - React version mismatch

### ISSUE THREAD

**Issue by jamesdbruner** [davidcetinkaya/embla-carousel#77]
@davidcetinkaya If you go spin up a codesandbox to try out embla (react) [like I did](https://codesandbox.io/s/awesome-hofstadter-wdn4f?file=/package.json:221-228) you'll get a react and react-dom version mismatch since embla has it's own react and react-dom dependencies. Would it not make sense to have these be dev dependencies? In that codesandbox example if you change the react and react-dom versions to `16.13.1` then the slider works as intended.

**Comment by davidcetinkaya** [comment]
Hello @jamesdbruner,

Thank you for noticing this. I only have to bump `react` to `16.13.1` to make it work. This is because the `react-dom` package is only used in a test file. I've released v.3.0.19 which should solve this issue.

Give it a go and let me know if it helps!

Best,
David

**Comment by jamesdbruner** [comment]
@davidcetinkaya First of all, that was an insanely fast response. That did fix the issue, thank you so much for doing that! 

Embla is honestly the best carousel I've seen in a decade of web development, so kudos to you and everyone who's contributed.

**Comment by davidcetinkaya** [comment]
Your timing was good, I was fixing some small stuff on the documentation page when you submitted the issue 😉.

Thank you @jamesdbruner and nice catch with the dependencies. Enjoy 🙂!

Kindly,
David
