### ISSUE TITLE
Conflicting names for type and function

### ISSUE THREAD

**Issue by korsvanloon** [davidcetinkaya/embla-carousel#78]
Both the function EmblaCarousel and the type are exported with the same name which results in the type not being able to import.

```typescript
export declare type EmblaCarousel = {
    canScrollNext: () => boolean;
  ...
};
declare function EmblaCarousel(sliderRoot: HTMLElement, userOptions?: EmblaOptions): EmblaCarousel;
export default EmblaCarousel;
```

Renaming either the type or the function name would fix this.

I tried to do something similar as in `react.ts`:

```typescript
import { EmblaCarousel as EmblaCarouselType } from '../vanilla';
```

But that still give me errors.

As a workaround I could do this:

```typescript
import EmblaCarousel from 'embla-carousel'
type EmblaCarouselType = ReturnType<typeof EmblaCarousel>
```

**Comment by davidcetinkaya** [comment]
Hello @korsvanloon,
Thank you for your suggestion. I decided to add the `Type` suffix to all types. So this is how the index.ts file turned out based on your suggestion:

```typescript
export { EmblaOptions as EmblaOptionsType } from './vanilla/components/options'
export { EmblaEvent as EmblaEventType } from './vanilla/components/eventEmitter'
export { EmblaCarousel as EmblaCarouselType } from './vanilla'

export { default } from './vanilla'
export { useEmblaCarousel } from './react'
```
So release [v3.0.20](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.20) should include what you need. 

Give it a go and let me know if it helps!
David

**Comment by davidcetinkaya** [comment]
@korsvanloon have you had a chance to try the [new type exports](https://github.com/davidcetinkaya/embla-carousel/issues/78#issuecomment-662035212)?

**Comment by davidcetinkaya** [comment]
@korsvanloon I'm closing this as resolved. Feel free to re-open this issue if needed.

Kindly,
David
