### ISSUE TITLE
Improve the documentation by providing a full example of code?

### ISSUE THREAD

**Issue by michaelrambeau** [davidcetinkaya/embla-carousel#8]
Hello again David @davidcetinkaya 
As mentioned in _Best of JavaScript_ issue (https://github.com/michaelrambeau/bestofjs/issues/237), I think you could improve the documentation by providing a full example of markup and JavaScript code.

You could use something like https://codepen.io and embed the "pen" directly in the demo page.

I'm asking because it took me some time to realize that I have to bind by myself the "Next" and "Previous" buttons to Embla methods.

Thank you for your attention!

**Comment by davidcetinkaya** [comment]
Hello Michael @michaelrambeau 
Thank you for submitting this issue and pointing that out!

I've created a [CodeSandbox](https://codesandbox.io/) with a full example of markup and JavaScript code. You'll find these links on both the [demo](https://davidcetinkaya.github.io/embla-carousel/) page and in the [docs](https://github.com/davidcetinkaya/embla-carousel).

Please take a look at the attached screenshots. I'd very much appreciate if you could confirm that this is the improvement you're looking for.

<img width="1286" alt="codesandbox-1" src="https://user-images.githubusercontent.com/11529148/58631209-21097b00-82e2-11e9-80f7-83ba380e33f4.png">

<img width="971" alt="codesandbox-2" src="https://user-images.githubusercontent.com/11529148/58631217-2666c580-82e2-11e9-831b-8dfadd8a25a8.png">

**Comment by michaelrambeau** [comment]
Sorry for the late feedback David, that looks good, thank you for your efforts!

It's not related but it's something I noticed when I checked the demo on CodeSandbox: when the loop mode is off, why the previous button is displayed on the first slide, since it triggers nothing? Should it be automatically hidden or disabled?

**Comment by davidcetinkaya** [comment]
Hi @michaelrambeau,
No worries, thanks for taking the time to check it out and I'm glad that the CodeSandbox links helped 😃.

At the time of writing Embla Carousel doesn't provide any **previous/next** button states. It just provides following methods and the rest is up to the user:

```javascript
embla.previous()
embla.next()
```

Just so I understand your question correctly, are you suggesting that:

1. I should implement an **enabled/disabled** state for the **previous/next** buttons on the CodeSandbox example to show an example of how to achieve this.
2. Or that I should build this feature into the Embla core?

Thank you 👍!

**Comment by michaelrambeau** [comment]
@davidcetinkaya I was trying to update the example on CodeSandbox (which is very useful to play with Embla by the way) to try to add the behavior I described.

Now I can use the following methods:

- `groupedIndexes()`
- `selectedIndex()`

Just an idea: maybe `embla` object could expose some convenient methods or properties like `isFirstSlide`, `isLastSlide`, `hasPreviousSlide` and `hasNextSlide` to make the task more convenient?

Thank you and sorry if I miss something obvious.

I can close this issue and open a new thread if you prefer.

**Comment by davidcetinkaya** [comment]
Hello again Michael @michaelrambeau,

Good Idea! Please open a new issue so we can keep the discussion relevant to the  topic 🙂.

You can just copy paste the question and I’d be very happy to help you with this 👍🏻.

I’m closing this issue and thanks a ton for reporting this Michael, I think your idea really improved things ⭐️.
