### ISSUE TITLE
Question: Is there a way to reset the autoplay timer when clicking dots/scrollNext

### ISSUE THREAD

**Issue by jodiedoubleday** [davidcetinkaya/embla-carousel#80]
Noticed this on the demo as well, but if I have autoplay on but click on the next arrow, the timing function of the autoplay doesn't reset. Instead, the timer still goes resulting in (depending on when you clicked on the next arrow immediately skip the image after.

(sorry this is hard to explain)

**Comment by davidcetinkaya** [comment]
Hello Jodie @jodiedoubleday,

Would you mind sharing the link to the demo you’re mentioning? Also, what’s the desired behavior in your opinion?

Kindly
David

**Comment by davidcetinkaya** [comment]
@jodiedoubleday do you want to pursue this?

Best,
David

**Comment by davidcetinkaya** [comment]
Hello again @jodiedoubleday.

I'm closing this issue for now. Feel free to re-open this issue if you want to pursue this.

Best,
David

**Comment by KonstantinSchuette** [comment]
So I'd like to reopen this post, because I think many people will also have this issue.
I'm using the "Inspiration Autoplay" example, I just commented this line out:
`embla.on("pointerDown", stop);`
https://codesandbox.io/s/embla-carousel-autoplay-react-forked-n3g44?file=/src/js/EmblaCarousel.js

My goal is, that you can slide through the slides manually and still use the autoplay function.
But if you slide manually at 3500ms, 500ms afterwards the autoplay func also slides.
So every time you slide manually you should reset the timeout of the autoplay.
I'm a newb in React, so I don't know how to make this happen.

**Comment by davidcetinkaya** [comment]
Hello Dewey (@KonstantinSchuette),

Thank you for your question. Wouldn't this do the trick?

```js
useEffect(() => {
  if (!embla) return;
  onSelect();
  embla.on("select", onSelect)
  embla.on("pointerDown", stop)  // <-- Comment this line in again
  embla.on("pointerUp", play);  // <-- Play again as soon as the user has released the pointer
}, [
  embla,
  onSelect,
  stop,
  play // <-- Add play to dependecies here
]);
```

Let me know if it helps.

Best,
David

**Comment by KonstantinSchuette** [comment]
> Hello Dewey (@KonstantinSchuette),
> 
> Thank you for your question. Wouldn't this do the trick?
> 
> ```js
> useEffect(() => {
>   if (!embla) return;
>   onSelect();
>   embla.on("select", onSelect)
>   embla.on("pointerDown", stop)  // <-- Comment this line in again
>   embla.on("pointerUp", play);  // <-- Play again as soon as the user has released the pointer
> }, [
>   embla,
>   onSelect,
>   stop,
>   play // <-- Add play to dependecies here
> ]);
> ```
> 
> Let me know if it helps.
> 
> Best,
> David

This works perfect, thank you!

**Comment by davidcetinkaya** [comment]
Glad to hear that @KonstantinSchuette, enjoy!

**Comment by plettj** [comment]
If anyone lands here coming from `shadcn/ui`, I've written a fix for the carousel component [here](https://github.com/shadcn-ui/ui/pull/2812#issuecomment-2845462331). Enjoy!

In case you just want the relevant React code snippet:
```ts
const scrollTo = React.useCallback(
    (index: number) => {
      if (index === api?.selectedScrollSnap()) return;
      const autoplay = api?.plugins()?.autoplay;
      autoplay?.reset();
      api?.scrollTo(index);
    },
    [api]
  );
```
