### ISSUE TITLE
React, carousel not working with fetched images

### ISSUE THREAD

**Issue by misshu1** [davidcetinkaya/embla-carousel#81]
I'm not able to use the carousel with photos fetched from outside my project.
Getting the following error:

```
scrollTarget.ts:41 Uncaught TypeError: Cannot read property 'index' of undefined
    at findTargetSnap (scrollTarget.ts:41)
    at Object.byDistance (scrollTarget.ts:73)
    at allowedForce (dragHandler.ts:106)
    at HTMLDocument.up (dragHandler.ts:167)
```

To make the carousel work I have to do a workaround like 

```jsx
{images.length !== 0 && (
    <Carousel images={images} />
)}
```

I don't think that's normal.

**Comment by davidcetinkaya** [comment]
Hello Andrei (@misshu1),

Thank you for opening this issue. Initializing an empty carousel without any slides is working fine. But the error you mention happens when I start dragging an empty carousel (without any slides). I'll see what I can do to fix that.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hello again Andrei (@misshu1),

I've released a patch fix with [version 3.0.23](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.23). Dragging a carousel with no slides shouldn't trigger the error anymore. 

Please note that you might need to tell Embla that the slide count has changed when you're done fetching your images. One way to do it would be:

```javascript
useEffect(() => {
  if (embla) embla.reInit()
}, [embla, images])
```

Please try it out and let me know if it works.

Best,
David

**Comment by misshu1** [comment]
Hey, sorry for the delay, works now :)

**Comment by davidcetinkaya** [comment]
Thanks for confirming that it works Andrei (@misshu1).

Enjoy and cheers!
David
