### ISSUE TITLE
Text cannot be selected when `draggable` = false

### ISSUE THREAD

**Issue by S1SYPHOS** [davidcetinkaya/embla-carousel#87]
Hey there,
I just checked this out and really like its simplicity and freedom of choice!

Title says it all though, I can't select text inside a slider when `draggable: false`. Any pointer in the right direction is appreciated. Currently I'm using a minimal setup (see website under 'Installation').

Cheers,
S1SYPHOS

**Comment by davidcetinkaya** [comment]
Hello Martin @S1SYPHOS,

Thank you for opening this issue. I’m going to try it out and will let you know if I can reproduce it and when I have something. Thanks for your patience.

Best 
David

**Comment by davidcetinkaya** [comment]
Hi again @S1SYPHOS,

Thank you for your patience. I can confirm that this is a bug and will fix this as soon as possible. Nice catch 🙂.

Best,
David

**Comment by davidcetinkaya** [comment]
Hello @S1SYPHOS,

[Version 4.0.3](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.3) includes a fix for this issue. I would appreciate if you could try it out and let me know if it's working as intended.

Thanks in advance,
David

**Comment by S1SYPHOS** [comment]
I'll do that, thanks for letting me know!

**Comment by S1SYPHOS** [comment]
Works as expected now, good job!

**Comment by davidcetinkaya** [comment]
Thanks @S1SYPHOS, enjoy 👍🏻!
