### ISSUE TITLE
Embla ref is not initialized correctly if component returns null at the first render

### ISSUE THREAD

**Issue by olushchik** [davidcetinkaya/embla-carousel#91]
Hi, David,

I'm trying to migrate my components from old v2.9 with class setup to the latest version of Embla with hook and I ran into the issue which described in the title. Please see the [demonstration](https://codesandbox.io/s/embla-carousel-default-react-forked-wj7hw?file=/src/js/EmblaCarousel.js). Is it a bug or expected behavior?

**Comment by olushchik** [comment]
Hi, David,

Looks perfect! I will wait for a new version with this fix :) Thanks!

**Comment by davidcetinkaya** [comment]
Thanks a lot for sharing your thoughts Felix @xiel. I agree that both things you mention need attention.

Regarding the options property with the inline object being passed, I’m thinking that a shallow object comparison could solve this (the Embla options object is flat), so we could store options in a red and only reinit Embla when options actually change.

What’s your thoughts about this suggestion?

Best
David

**Comment by olushchik** [comment]
Hi, David,

When can we expect a new version with this fix? :)

**Comment by davidcetinkaya** [comment]
Hello Oleg (@olushchik),

I'm working on this and making progress. But I wouldn't want to rush this because that will probably introduce unwanted bugs. I'll let you know as soon as I have something. Thank you for your patience.

Kindly
David

**Comment by davidcetinkaya** [comment]
So here's the current draft @olushchik, @xiel. Any thoughts or feedback?

```ts
function useEmblaCarousel(
  options: EmblaOptions = {},
): [FC<PropType>, EmblaCarouselType?] {
  const [embla, setEmbla] = useState<EmblaCarouselType>()
  const [container, setContainer] = useState<HTMLElement>()
  const storedOptions = useRef<EmblaOptions>(options)

  const hasOptionsChanged = useCallback(
    (options: EmblaOptions) => {
      if (!areEqualShallow(storedOptions.current, options)) {
        storedOptions.current = options
      }
      return storedOptions.current
    },
    [options],
  )

  useEffect(() => {
    if (canUseDOM() && container) {
      embla?.destroy()
      setEmbla(EmblaCarousel(container, options))
    }
    return () => embla?.destroy()
  }, [container, hasOptionsChanged(options)])

  const Carousel: FC<PropType> = useCallback(
    ({ htmlTagName = 'div', className, children }) => {
      return createElement(
        htmlTagName,
        {
          className,
          ref: setContainer,
          style: { overflow: 'hidden' },
        },
        children,
      )
    },
    [],
  )

  return [Carousel, embla]
}
```

Best
David

**Comment by xiel** [comment]
Few minor things:
1. shadowing of options variable in hasOptionsChanged & use of complex expressions is discouraged in deps array `[..., hasOptionsChanged(options)]`
2. embla state is not reset to undefined when it is not available anymore (eg. container unmounted)
3. duplication - no need to call destroy before set (cleanup is always called first anyway)

I can also recommend using [eslint rule of hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks), which helps to catch that all dependency array are up-to-date.

Here is a in my view corrected version:

```ts
  const [embla, setEmbla] = useState<EmblaCarouselType>()
  const [container, setContainer] = useState<HTMLElement>()
  const storedOptions = useRef<EmblaOptions>(options)
  const activeOptions = useMemo<EmblaOptions>(() => {
    if (!areEqualShallow(storedOptions.current, options)) {
      storedOptions.current = options
    }
    return storedOptions.current
  }, [storedOptions, options])

  useEffect(() => {
    if (canUseDOM() && container) {
      const newEmbla = EmblaCarousel(container, activeOptions)
      setEmbla(newEmbla)
      return () => newEmbla.destroy()
    } else {
      setEmbla(undefined)
    }
  }, [container, activeOptions])
```

Cheers,
– Felix

**Comment by davidcetinkaya** [comment]
Hello Felix (@xiel),
Thanks a bunch for taking the time to share your feedback. Regarding the list:

1. You're right! I rushed it a bit and the `useMemo` as you suggest is a better solution.
2. Nice catch. Rushed it here too. Setting this to `undefined` will remove the need of the duplicate destroy.
3. Point 2 solves this.

Again, thanks a lot!

**Comment by davidcetinkaya** [comment]
Hello Oleg (@olushchik),

Please read the [migration guide here](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.0) and update to the latest version of Embla Carousel. The hook should now work as expected and react to when its container changes.

Let me know if this helps.

Cheers
David

**Comment by davidcetinkaya** [comment]
Hello Oleg (@olushchik),

Have you had a chance to try the new version out yet?

Best
David

**Comment by olushchik** [comment]
Hi, David,

Yes, I updated our project to new version and all looks good 👍 Thanks for your work!

Oleg

**Comment by davidcetinkaya** [comment]
Glad to hear that it’s working. And thank you for the feedback. Most of the cred goes to @xiel for his contributions.

Enjoy!
David
