### ISSUE TITLE
Is there a way to link to a specific slide?

### ISSUE THREAD

**Issue by jodiedoubleday** [davidcetinkaya/embla-carousel#95]
If I have an image carousel of 10 images, and I want to send a link to someone, which specifically links them to the 6th image in the carousel is there a way to do this with Embla?

I was thinking maybe ID on each child which you can link to via the URL i.e www.example.com/carousel#image6

Also want to take this time to say loving your work on this carousel! Thank you!

**Comment by davidcetinkaya** [comment]
Hello Jodie (@jodiedoubleday), thanks a lot 🙂.

It should be quite possible to achieve. This is not built in to the core though, so I'm thinking you have to do something along these lines:

1. Grab the number from the url www.example.com/carousel#image6 and parse it so you get the number and store it in a variable. Let's say `slideToShow` In this case it would be nr. 6.
2. Scroll the carousel in view.
3. Set the `startIndex` option to the number you just stored to start at that slide like so: 

```javascript
const options = { startIndex: slideToShow - 1 } // Where the -1 is there to account for the zero based slide index.
const embla = EmblaCarousel(elementNode, options)
```

Let me know if this helps and if I'm understanding you correctly.

Best,
David

**Comment by jodiedoubleday** [comment]
Awesome thanks @davidcetinkaya I'll give it a try.

**Comment by davidcetinkaya** [comment]
I’m glad if it helped. Let me know how it goes @jodiedoubleday.

Best 
David

**Comment by mariocsantos** [comment]
I have something like the example, I know the slide index, but my carousel has items with dynamic widths, and the `slideScroll` props is `auto`, so the snap index is different from the slide index, could help me? Thank you.

**Comment by davidjerleke** [comment]
Hi @mariocsantos,

This is a feature that will be implemented but I can’t say when. See [this comment](https://github.com/davidjerleke/embla-carousel/discussions/437#discussioncomment-5103378) in:

- #437 

Best,
David
