### ISSUE TITLE
Update examples on CodeSandbox for React

### ISSUE THREAD

**Issue by RectoVersoDev** [davidcetinkaya/embla-carousel#96]
Hello,

First of all, thank you for your excellent work ! This is the best carousel I've ever used. 🔥

Since the 4.0.0 update the previous code doesn't work anymore for arrows & dots for React.

If you could update the CodeSandbox examples it would be awesome!

**Comment by davidcetinkaya** [comment]
Hello @RectoVersoDev,

Thank you for the awesome feedback =}. Are you sure? I updated the React CodeSandboxes to use the new ref approach yesterday. Maybe cache in your browser is causing this?

You mean this CodeSandbox right?
https://codesandbox.io/embed/embla-carousel-arrows-dots-react-z5fbs

Kindly,
David

**Comment by RectoVersoDev** [comment]
Ah yes... I see the new code now! Sorry for the inconvenience and thank you for the quick answer! I close the issue

**Comment by davidcetinkaya** [comment]
Nice to hear that. Thanks and enjoy 🙂!
